<?php $this->partial('layouts/common/header');?>
<!--<section class="container">
<?php //echo $this->getContent(); ?>
</section>-->
<div class="container-fluid">
    <div class="starter-template row">
        <div class="col-md-12">
            <div class="container">
                <?php $this->partial('layouts/common/message'); ?>
                <?php echo $this->getContent(); ?>
            </div>
        </div>
    </div>
</div><!-- /.container -->

<?php $this->partial('layouts/common/footer');?>
