<div class="panel-heading"><i class="fa fa-shield"></i> Reset Password</div>
<div class="panel-body">
    <div class="col-sm-8">
        <form id="reset-password" class="form-horizontal" method="post">
            <fieldset>
                <?php $form->renderBootstrap('current_password'); ?>
                <?php $form->renderBootstrap('new_password'); ?>
                <?php $form->renderBootstrap('repeat_password'); ?>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <?php echo $form->render('submit'); ?>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>