<style>
    .form-sub-category {
        margin-left: 40px;
    }
</style>
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Category</h3>
    </div>
    <div class="panel-body">
        <form class="form-control-static" method="post">
            <div class="tab-wrapper">
                <div class="col-xs-6 no-pad-left">
                    <?php $form->renderHorizental('category_title'); ?>
                    <div class="form-group">
                        <label>Parent Category</label>
                        <div class="tab-content-border" style="max-height: 300px; overflow: auto;border-top: 1px solid #DDD;">
                            <?php $form->renderCategory(array('esc' => $categoryId)); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label><?php echo $form->render('category_mark_parent'); ?> This is a parent category</label>
                    </div>
                    <?php $form->renderHorizental('category_status'); ?>
                </div>
            </div>
            <div class="col-lg-12 no-pad">
                <?php echo $form->render('submit'); ?>
                <?php echo $this->tag->linkTo(array('/admin/vendors/category', 'Back', 'class' => 'btn btn-info')); ?>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    jQuery(function () {
        jQuery('input[type="radio"].form-cat').click(function () {
            jQuery('input[type="checkbox"]#category_mark_parent').prop('checked', false);
        });

        jQuery('input[type="checkbox"]#category_mark_parent').click(function () {
            jQuery('input[type="radio"].form-cat').prop('checked', false);
        });
    });
</script>



