<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Edit Vendor</h3>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post">
            <fieldset>
                <legend><h3>About Vendor</h3></legend>
                <div class="tab-wrapper">
                    <div class="col-xs-8">
                        <?php $form->renderBootstrap('vendor_business_name'); ?>
                        <?php $form->renderBootstrap('vendor_category'); ?>
                        <?php $form->renderBootstrap('vendor_tour_activity_type[]'); ?>
                        <?php $form->renderBootstrap('vendor_country'); ?>
                        <?php $form->renderBootstrap('vendor_state'); ?>
                        <?php $form->renderBootstrap('vendor_city'); ?>
                        <?php $form->renderBootstrap('vendor_status'); ?>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend><h3>Contact Detail</h3></legend>
                <div class="tab-wrapper">
                    <div class="col-xs-8">
                        <?php $form->renderBootstrap('vendor_job_title'); ?>
                        <?php $form->renderBootstrap('vendor_first_name'); ?>
                        <?php $form->renderBootstrap('vendor_last_name'); ?>
                        <?php $form->renderBootstrap('vendor_email'); ?>
                        <?php $form->renderBootstrap('vendor_phone'); ?>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend><h3>Additional Details</h3></legend>
                <div class="tab-wrapper">
                    <div class="col-xs-8">
                        <div class="form-group">
                            <label for="vendor_is_trip_advisor" class="col-sm-4 control-label">Are you listed on Trip Advisor?</label>
                            <div class="col-sm-8">
                                <?php
                                foreach (array("y" => "Yes", "n" => "No", "ns" => "Not Sure") as $tadvKey => $tadv) {
                                    $attribute = array(
                                        "vendor_is_trip_advisor",
                                        "value" => $tadvKey
                                    );
                                    if ($formType == 'edit') {
                                        if ($tadvKey == $vendor->isTripAdv) {
                                            $attribute["checked"] = "checked";
                                        }
                                    }
                                    $attribute["onclick"] = "disableAdvisorLink(this);";
                                    ?>
                                    <div><?php echo \Phalcon\Tag::radioField($attribute); ?> <?php echo $tadv; ?></div>
                                <?php } ?>
                            </div>
                        </div>
                        <?php $form->renderBootstrap('vendor_trip_advisor_link'); ?>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend><h3><?php echo $formType == 'edit' ? 'Reset ' : '';?>Password</h3></legend>
                <div class="tab-wrapper">
                    <div class="col-xs-8">
                        <?php $form->renderBootstrap('vendor_password'); ?>
                        <?php $form->renderBootstrap('vendor_re_password'); ?>
                    </div>
                </div>
            </fieldset>
            <div class="col-lg-12 no-pad">
                <?php echo $form->render('submit'); ?>
                <?php echo $this->tag->linkTo(array('/admin/vendors', 'Cancel', 'class' => 'btn btn-primary')); ?>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    jQuery(function () {
        jQuery("#vendor_country").change(function () {
            var countryId = jQuery(this).val();
            var url = "<?php echo $this->url->get('/ajax/renderstate/'); ?>";
            var stateElement = jQuery("#vendor_state");
            jQuery.get(url + countryId, function (data) {
                var response = jQuery.parseJSON(data);
                if (typeof response.states != 'undefined' && response.states.length > 0) {
                    stateElement.html("<option value=''>-- Select Your State --</option>");
                    for (var s in response.states) {
                        stateElement.append("<option value='" + response.states[s].stateId + "'>" + response.states[s].stateName + "</option>");
                    }
                }
            });
        });
    });
    function disableAdvisorLink(element) {
        var advisorLinkElement = jQuery("#vendor_trip_advisor_link");
        if (element.value != 'y') {
            if (!advisorLinkElement.is(":disabled")) {
                advisorLinkElement.val("").prop("disabled", true);
            }
        } else {
            advisorLinkElement.prop("disabled", false);
        }
    }
</script>