<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $formType == 'edit' ? 'Edit ' : 'New '; ?>Tour & Activity Type</h3>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post">
            <div class="tab-wrapper">
                <div class="col-xs-8">
                    <?php $form->renderBootstrap('tour_type_title'); ?>
                    <?php $form->renderBootstrap('tour_type_status'); ?>
                </div>
            </div>
            <div class="col-lg-12 no-pad">
                <?php echo $form->render('submit'); ?>
                <?php echo $this->tag->linkTo(array('/admin/vendors/touractivities', 'Back', 'class' => 'btn btn-default')); ?>
            </div>
        </form>
    </div>
</div>
