<?php echo $this->tag->stylesheetLink($this->url->getStatic(COMMON_DIR . "weather-plugin/weather.css")); ?>
<!-- DYNAMIC BANNER IMAGES BEGIN -->
		<!-- @author Algie Caballes -->
    	<header class="header">
			<div class="s-banner">
				<div class="banner-caption">
					<!--<h1>Book tickets for top attractions around the world</h1>-->
				</div>
				<div id="transition-timer-carousel" class="carousel slide transition-timer-carousel" data-ride="carousel">
				<div class="carousel-inner">
					<!-- banner images display -->
					<?php if ($bannerImages->count() > 0): ?>
						<?php foreach ($bannerImages as $key => $banner): ?>
							<div class="item <?php if ($key == 0) { echo 'active'; } ?>">
								<a href="<?php echo $banner->bannerLink; ?>" target="_blank"><img src="<?php echo $banner->getBannerUri(); ?>" alt=""style="width:100%; "/></a>
								<div class="carousel-caption">
									<div class="carousel-caption" style="top: 0; bottom: 0;">
										<h1><?php echo $banner->bannerCaption; ?></h1>
									</div>
								</div>
							</div>
						<?php endforeach; ?>
					<?php else: ?>
						<div class="item">
							<img src="<?php echo $this->url->getStatic(FRONT_END_DIR . 'images/banner-img.png'); ?>"/> 
						</div>
					<?php endif; ?>
				</div>
			</div>   
		</div>
	</header>

<section class="tour-content">
    <div class="container">
        <div class="tab-pane" style="position:relative;margin-top: 3%;">
            <?php if ($groupVendors && $groupVendors->count() > 0) { ?>
                <ul class="nav nav-tabs" id="gtabs">
                    <?php foreach ($groupVendors as $groupVendor) { ?>
                        <li><a id="<?php echo $groupVendor->groupId; ?>" class="tours"><?php echo $groupVendor->group->groupName; ?></a></li>
                        <?php }?>
                </ul>
<!--             <hr style="position:absolute;top: 28px; left: 0px;width:100%;border-top: solid 1px #332525;">-->
                <?php } else { ?>
                No Data
                <?php } ?>
               
                <div class="pull-right grid-btn">
                <div class="btn-group" aria-label="Tour View Group" role="group">
                <button class="btn btn-default btn-tour-view active" id="btn1" data-view-target="grid" type="button">
                <span class="glyphicon glyphicon-th"></span>
                </button>
                <button class="btn btn-default btn-tour-view" id="btn2" data-view-target="list" type="button">
                <span class="glyphicon glyphicon-list"></span>
                </button>
                </div>
                </div>
          <div class="clearfix"></div>
                
                <div class="row tour-box-container" id="form1" style="display:none" >
                  <?php if ($groupTours && $groupTours->count() > 0) { ?>
                    <?php foreach ($groupTours as $groupTour) { ?>
                   
               <div class="tour tour-<?php echo $groupTour->groupId; ?>">
                  
                         <div id="grid" class="tour-box-view show" >
                   <?php  if($storeVendor->themeBackground== 1){ ?>
                       
               <div class="col-xs-6 col-sm-4">
                    <div class="tour-box-smr clearfix">
                   <img style="width:100%; height:300px;" src="<?php echo $groupTour->tour->getDefaultImage() ? $groupTour->tour->getDefaultImage()->getImageUri('thumb') : ''; ?>" /> 


                   <div class="tour-box-smr-detail">
                      <div class="tour-box-smr-review">
                         <i class="fa fa-star" aria-hidden="true"></i> 
<i class="fa fa-star" aria-hidden="true"></i>
                             <i class="fa fa-star" aria-
hidden="true"></i> <i class="fa fa-star" aria-hidden="true"></i>
                                   <span>(1403)</span>
                                      </div>

                    <div class="tour-box-smr-dtls">
                    <a href="<?php echo $groupTour->tour->getUri(); ?>"><?php echo $groupTour->tour->tourTitle; ?></a>

                    </div>
                    
                    <div class="tour-box-smr-detail-bottom clearfix">
                    <div class="tour-box-smr-detail-bottom-lft">Fellow 
LLC •&nbsp;<?php 
					if($groupTour->tour->tourCity){ 
echo $groupTour->tour->tourCity; } else { echo '';}
					?>
                    </div>
                    <div class="tour-box-smr-detail-bottom-rht w-col">
				   <?php if ($groupTour->tour->tourPrice->hasDiscount() || $groupTour->tour->tourPrice->hasOffers()){ ?>
 

                   <?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?>
                   <?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice(true)); ?>                   
                       <?php } else { ?> 
                   <?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?>
                   <?php } ?>
                  </div>
                  
                    <?php if ($groupTour->tour->tourPrice->hasDiscount() || $groupTour->tour->tourPrice->hasOffers()) { ?>
                    <div class="tour-box-smr-detail-bottom-rht"><span><?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?></span>
                        <?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice(true)); ?><span><?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?></span>
                     <?php } ?>
                    </div>
                    </div>
                    
                    
                    </div>
                    <div class="tour-box-smr-icon2"><i class="fa fa-heart" aria-hidden="true"></i></div>
                   <!-- <div class="tour-box-smr-icon1" style="margin-left:8px;"><span>45%</span> OFF</div>-->
                    </div>
                    </div>
                   
                   <?php }
                     else { ?>
                   
                   <div class="col-xs-6 col-sm-4">
<div class="tour-box-smr clearfix">
<img style="width:100%; height:300px;" src="<?php echo $groupTour->tour->getDefaultImage() ? $groupTour->tour->getDefaultImage()->getImageUri('thumb') : ''; ?>" />

<div class="tour-box-smr-detail">
<div class="tour-box-smr-review">
	<ul class="review">
		<li class="text-yellow">
			<div id="star-rate-box-<?php echo $groupTour->tour->tourId; ?>"></div>
			<script>jQuery(function () {
				jQuery('#star-rate-box-<?php echo $groupTour->tour->tourId; ?>').rateYo({rating: <?php echo $groupTour->tour->tourReviews ? $groupTour->tour->tourReviews->count() : 0; ?>, starWidth: "15px", readOnly: true, ratedFill: "#ede811"});
			});</script>
		</li>
		<li class="review-count">(<?php echo $groupTour->tour->tourReviews ? $groupTour->tour->tourReviews->count() : 0; ?>)</li>
	</ul>
</div>

<div class="tour-box-smr-dtls">
 <a href="<?php echo $groupTour->tour->getUri(); ?>"><?php echo 
$groupTour->tour->tourTitle; ?></a>
</div>

<div class="tour-box-smr-detail-bottom clearfix">
<div class="tour-box-smr-detail-bottom-lft">
	Location:&nbsp;<?php 
					if($groupTour->tour->tourCity){ echo $groupTour->tour->tourCity; } else { echo '';}
					?><br>Duration: <?php echo $groupTour->tour->tourDuration->lengthTypeText;?>
</div>
<div class="tour-box-smr-detail-bottom-rht w-col">
				   <?php if ($groupTour->tour->tourPrice->hasDiscount() || $groupTour->tour->tourPrice->hasOffers()) 
{ ?>
                   <?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?>
                   <?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice(true)); ?>                   
                       <?php } else { ?> 
                   <?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?>
                   <?php } ?>
                  </div>
                  
                    <?php if ($groupTour->tour->tourPrice->hasDiscount
() || $groupTour->tour->tourPrice->hasOffers()) { ?>
                    <div class="tour-box-smr-detail-bottom-
rht"><span><?php echo \Tourpage\Helpers\Utils::formatCurrency
($groupTour->tour->tourPrice->getPrice()); ?></span><?php echo 
\Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice(true)); ?><span><?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?></span>
                 <?php } ?>
                    </div>
                    </div>
                    
                    
                    </div>
                    <div class="tour-box-smr-icon2"><i class="fa fa-
heart" aria-hidden="true"></i></div>
<!--<div class="tour-box-smr-icon1"><span>45%</span> OFF</div>-->
</div>

</div>
                   
                   <?php } ?>    
                        </div>              
             
                    <?php } ?>
                   
                    <?php } ?>
              
               </div>
                 </div>
              
                

            
            
            
            
            <div class="tab-contents" id="form2" >
            
                <?php if ($groupTours && $groupTours->count() > 0) { ?>
                    <?php foreach ($groupTours as $groupTour) { ?>
                        <div class="tour tour-<?php echo $groupTour->groupId; ?>">
                         <div class="tour-box clearfix">
                                <div class="col-md-3">
                                    <?php if ($groupTour->tour->tourPrice->hasDiscount() || $groupTour->tour->tourPrice->hasOffers()){ ?>
                                        <div class="sale-<?php echo $groupTour->groupId; ?>"style="position:absolute;top:15px;left:4px;background:url(<?php echo $this->url->getStatic(FRONT_END_DIR . 'images/sale.png'); ?>) center center no-repeat;height: 25px;width: 92px;padding-top:8px;padding-left:30px;color:#ffffff;font-size: 10px;font-weight: bold;">
                                            <?php echo $groupTour->tour->tourPrice->data->discount->price.'% OFF';?>
                                        </div>
                                        <?php } else { ?>
                                        <div class="sale-<?php echo $groupTour->groupId; ?>" style="position:absolute;top:15px;left:4px;height: 25px;width:92px;padding-top:8px;padding-left: 30px;color:#ffffff;font-size:10px;font-weight: bold;">&nbsp;
                                        </div>
                                        <?php } ?>
                                    <!--<a href="<?php #echo $groupTour->tour->getUri(); ?>"><img src="<?php #echo $groupTour->tour->getDefaultImage() ? $groupTour->tour->getDefaultImage()->getImageUri('thumb') : ''; ?>" width="253" height="225"/></a>-->
									<a href="javascript:redirectToSpecificPage('<?php echo "/".strtolower((preg_replace('/[\s_]/', '', $storeVendor->businessName)))."/ourtours/".$groupTour->tour->tourSlug; ?>', '<?php echo $groupTour->tourId; ?>', 'tour_id')"><img src="<?php echo $groupTour->tour->getDefaultImage() ? $groupTour->tour->getDefaultImage()->getImageUri('thumb') : ''; ?>" width="253" height="225"/></a>
                                </div>
                                <div class="col-md-7">
                                    <section class="content-header">
                                        <h1><a href="javascript:redirectToSpecificPage('<?php echo "/".strtolower((preg_replace('/[\s_]/', '', $storeVendor->businessName)))."/ourtours/".$groupTour->tour->tourSlug; ?>', '<?php echo $groupTour->tourId; ?>', 'tour_id')"><?php echo $groupTour->tour->tourTitle;?></a></h1>
                                        <ul class="review">
                                            <li class="text-yellow">
                                                <div id="star-rate-grid-<?php echo $groupTour->tour->tourId; ?>"></div>
                                                <script>jQuery(function() {
                                                    jQuery('#star-rate-grid-<?php echo $groupTour->tour->tourId; ?>').rateYo({rating: <?php echo $groupTour->tour->tourReviews ? $groupTour->tour->tourReviews->count() : 0; ?>, starWidth: "15px", readOnly: true, ratedFill:"#ede811"});
                                                });</script>
                                            </li>
 <li class="review-count">(<?php echo $groupTour->tour->tourReviews ? $groupTour->tour->tourReviews->count() : 0; ?>)</li>
</ul>
<div style="float: left; width:100%; margin-top: 10px; margin-bottom: 10px;">
<?php if ($groupTour->tour->tourAttributes->count() > 0) { ?>
<?php foreach ($groupTour->tour->tourAttributes as $tourAttribute) { ?>
 <?php if($tourAttribute->keyId == 2) { ?>
 <?php
                                                            
$attributeContent = \Tourpage\Helpers\Utils::decodeString($tourAttribute->attributeContent);
if (strlen($attributeContent) > 180) {
                                                                
$attributeContent = substr($attributeContent, 0, 180);
                                                                
$attributeContent .= '.. ';
                                                                
$attributeContent .= $this->tag->linkTo(array($groupTour->tour->getUri(), 'more', 'local' => false));

}
echo $attributeContent;
?>
                                                        <?php } ?>
                                                    <?php } ?>
                                                <?php } ?>
                                            <p>Location: <strong><?php  if($groupTour->tour->tourCity){ echo $groupTour->tour->tourCity; } else { echo '';}                                                  /*if($groupTour->tour->country->name){ echo ', '.$groupTour->tour->country->name;} 
else{ echo '';}*/?></strong>, Duration: <strong>
                                                    <?php echo $groupTour->tour->tourDuration->lengthTypeText;?>
                                                </strong></p>
                                        </div>
                                        <?php if($groupTour->tour->tourImages->count() > 0){ ?>
                                            <div id="tour-images" class="carousel tour-images">
                                                <div class="carousel-inner" role="listbox">
                                                    <?php
                                                        $fccatv = 1;
                                                        foreach ($groupTour->tour->tourImages as $tourImage) {
                                                        ?>
                                                        <div class="item<?php echo ($fccatv == 1 ? ' active' : ''); ?>">
                                                            <div class="tour-images-item">
                                                                <img src="<?php echo $tourImage->getImageUri('thumb');?>" style="width:50px;height:50px"/>
                                                            </div>
                                                        </div>
                                                        <?php $fccatv++; ?>
                                                        <?php } ?>
                                                </div>
                                                <!-- Controls -->
                                                <a class="left carousel-control" href="#tour-images" role="button" data-slide="prev">
                                                    <span class="glyphicon glyphicon-chevron-left left-box-control" aria-hidden="true"></span>
                                                    <span class="sr-only">&lt;</span>
                                                </a>
                                                <a class="right carousel-control" href="#tour-images" role="button" data-slide="next">
                                                    <span class="glyphicon glyphicon-chevron-right left-box-control" aria-hidden="true"></span>
                                                    <span class="sr-only">&gt;</span>
                                                </a>
                                        	</div>
                                        <?php } ?>
                                    </section>
                                </div>
                                <div class="col-md-2">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <?php if ($groupTour->tour->tourPrice->hasDiscount() || $groupTour->tour->tourPrice->hasOffers()) { ?>
                                                <div class="sale-button-<?php echo $groupTour->groupId; ?>" style="background:#ef3d23;color:#ffffff;font-size: 10px;font-weight:bold;text-align:center;height:20px;line-height:20px;margin-bottom:3px;">SALE</div>
                                                <?php } else { ?>
                                                <div class="sale-button-<?php echo $groupTour->groupId; ?>" style="color:#ffffff;font-size: 10px;font-weight: bold;text-align:center;height:20px;line-height:20px;margin-bottom:3px;">&nbsp;</div>
                                                <?php } ?>
                                            <?php if ($groupTour->tour->tourCapacity > 0) { ?>
                                                <div class="left_button-<?php echo $groupTour->groupId; ?>" style="background:#ed952e;color:#ffffff;font-size: 10px;font-weight:bold;text-align:center;height:20px;line-height:20px;"><?php echo 'Only'.$groupTour->tour->tourCapacity.' left'; ?>
                                                </div>
                                                <?php } else { ?>
                                                <div class="left_button-<?php echo $groupTour->groupId; ?>" style="color:#ffffff;font-size: 10px;font-weight: bold;text-align:center;height:20px;line-height:20px;">&nbsp;</div>
                                                <?php } ?>
                                        </div>
                                        <div class="col-md-6">
                                            <?php if (!$this->member->isFavoriteTour($groupTour->tourId)) { ?>
                                                <a href="#" class="text-red fav-tour" onclick="return addToFavTour('<?php echo $groupTour->tourId; ?>', '<?php echo $groupTour->vendorId; ?>');"><i class="glyphicon glyphicon-heart fa-lg" aria-hidden="true"></i></a>
                                                <?php } ?>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <ul class="price">
                                                <li class="text-info-from">From</li>
                                                <?php if ($groupTour->tour->tourPrice->hasDiscount() || $groupTour->tour->tourPrice->hasOffers()) { ?>
                                                    <li class="ori-price" style="font-size:16px;"><?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?></li>
                                                    <li class="text-info" style="color:#ef3d23;"><?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice(true)); ?></li>
                                                    <?php } else { ?>
                                                    <li class="ori-price" style="font-size:16px;text-decoration:none;">&nbsp;</li>
                                                    <li class="text-info"><?php echo \Tourpage\Helpers\Utils::formatCurrency($groupTour->tour->tourPrice->getPrice()); ?></li>
                                                    <?php } ?>
                                            </ul>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <p><br/></p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <!--<a href="<?php #echo $groupTour->tour->getUri(); ?>" class="btn-lg btn-block btn-book-tour">Book Now</a>-->
											<a href="javascript:redirectToSpecificPage('<?php echo "/".strtolower((preg_replace('/[\s_]/', '', $storeVendor->businessName)))."/ourtours/".$groupTour->tour->tourSlug; ?>', '<?php echo $groupTour->tourId; ?>', 'tour_id')" class="btn-lg btn-block btn-book-tour">Book Now</a>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>   
                        </div>
                        <?php } ?>
                        <article class="jumbotron no-tour text-center"></article>
                    <?php } else { ?>
                    <article class="jumbotron">No Tour Found</article>
                    <?php } ?>
            </div>
          
            <div class="clearfix"></div>
                 
        <div class="text-center tour-btn">
            <a  onClick="redirectTo('<?php echo $this->url->get('/store/tours/' . $storeVendor->vendorId); ?>');" class="btn-info btn-lg btn-all-tour">See All Tours</a>
       
    </div>
            
    </div>
    </div>
</section>
<section class="tour-options-content"> 
    <div class="container">       
        <!---------------------- SECOND ---------------------->
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="tour-reviews">
                            <h4>Customers Reviews &amp; Rating</h4>
                            <?php if ($reviews->count() > 0) { ?>
                                <?php foreach ($reviews as $review) { ?>
                                    <div class="tour-review-box clearfix" style="background:#ffffff;margin-top:5px;margin-bottom:5px;border: solid 1px #eee;">
                                        <div class="tour-img-154" style="padding:7px;">
                                            <?php
                                                $reviewerAvator = $this->url->getStatic(FRONT_END_DIR . 'images/reviewer_avatar_default.png');
                                                if ($review->isMember()) {
                                                    if ($review->memberTourReview && $review->memberTourReview->count() > 0) {
                                                        $reviewerAvator = $review->memberTourReview->member->getAvatarUri(\Tourpage\Models\Members::AVATAR_THUMB);
                                                    }
                                                }
                                                echo $this->tag->image(array(
                                                    $reviewerAvator,'height'=>'110px','width'=>'180px'
                                                ));
                                            ?>
                                        </div>
                                        <div class="tour-dels-154" style="padding:7px;">
                                            <div class="text-22-sm">
                                                <h4><?php echo \Tourpage\Helpers\Utils::decodeString($review->reviewByName); ?><span class="pull-right"></span></h4>
                                                <div class="col-sm-12" style="padding-left: 0;">
                                                    <ul class="review">
                                                        <li class="text-yellow">
                                                            <span id="star_count_<?php echo $review->reviewId; ?>" style="padding: 0;"></span>
                                                            <script>jQuery(function () {
                                                                jQuery('#star_count_<?php echo $review->reviewId; ?>').rateYo({rating: <?php echo $review->starCount; ?>, starWidth: "15px", readOnly: true, ratedFill: "#ede811"});
                                                            });</script>
                                                        </li>
                                                    </ul>
                                                    <p>
                                                        <?php
                                                            $reviewContent = \Tourpage\Helpers\Utils::decodeString($review->reviewContent);
                                                            if (strlen($reviewContent) > 200) {
                                                                $reviewContent = substr($reviewContent, 0, 200);
                                                                $reviewContent .= '.. ';
                                                                $reviewContent .= $this->tag->linkTo(array('#', 'more', 'local' => false));
                                                            }
                                                            echo $reviewContent;
                                                        ?>
                                                    </p>
                                                </div>                                    
                                            </div>
                                        </div>
                                    </div>
                                    <?php } ?>
                                <?php } else { ?>
                                <p>No one has given review</p>
                                <?php } ?>
                        </div>
                    </div><!-- /.col-sm-7 -->
                    <div class="col-sm-4">
                        <div class="tour-others">
                            <h4>You may Also Like</h4>
                            <?php //if ($review->isMember()) {
                                //if ($review->memberTourReview && $review->memberTourReview->count() > 0){?>
                            <?php if ($otherTours->count() > 0) { ?>
                                <?php
                                    foreach ($otherTours as $fromCategory) {
                                    ?>

                                    <div class="tour-similar-box clearfix" style="background:transparent;margin-top: 5px;margin-bottom: 5px;border: solid 1px #ccc;padding: 10px;">
                                        <div class="col-sm-6">
                                            <a href="javascript:redirectToSpecificPage('<?php echo "/".strtolower((preg_replace('/[\s_]/', '', $storeVendor->businessName)))."/ourtours/".$fromCategory->tour->tourSlug; ?>', '<?php echo $fromCategory->tour->tourId; ?>', 'tour_id')">
                                                <img src="<?php echo $fromCategory->tour->getDefaultImage() ? $fromCategory->tour->getDefaultImage()->getImageUri('thumb') : ''; ?>" style="width:160px;height:100px"/>
                                            </a>
                                        </div>
                                        <div class="col-sm-6">
                                            <ol>
                                                <li class="tit"><a href="javascript:redirectToSpecificPage('<?php echo "/".strtolower((preg_replace('/[\s_]/', '', $storeVendor->businessName)))."/ourtours/".$fromCategory->tour->tourSlug; ?>', '<?php echo $fromCategory->tour->tourId; ?>', 'tour_id')">
                                                        <?php //echo $fromCategory->tour->tourTitle; ?>
                                                        <?php
                                                            $tourTitle = $fromCategory->tour->tourTitle;
                                                            if (strlen($tourTitle) > 25) {
                                                                $tourTitle = substr($tourTitle, 0, 25);
                                                                $tourTitle .= '..';
                                                            }
                                                            echo $tourTitle;
                                                        ?>
                                                    </a>
                                                    <?php /*?><ul class="review">
                                                        <li class="text-yellow">
                                                        <span id="star_count_<?php echo $review->reviewId; ?>" style="padding: 0;"></span>
                                                        <script>
                                                        jQuery(function () {
                                                        jQuery('#star_count_<?php echo $review->reviewId; ?>').rateYo({rating: <?php echo $review->starCount; ?>, starWidth: "15px", readOnly: true});
                                                        });
                                                        </script>
                                                        </li> 
                                                    </ul><?php */?>
                                                </li>
                                                <li class="ven">By <a href="javascript:redirectToSpecificPage('<?php echo "/".strtolower((preg_replace('/[\s_]/', '', $storeVendor->businessName)))."/store"; ?>', '<?php echo $storeVendor->vendorId; ?>', 'vendor_id');"><?php echo $fromCategory->tour->tourVendor->vendor->firstName . ' ' . $fromCategory->tour->tourVendor->vendor->lastName; ?></a></li>            
                                            </ol>       
                                            <ul class="review">
                                                <li class="text-yellow">
                                                    <div id="star-rate-subgrid-<?php echo $fromCategory->tour->tourId; ?>"></div>
                                                    <script>jQuery(function () {
                                                        jQuery('#star-rate-subgrid-<?php echo $fromCategory->tour->tourId; ?>').rateYo({rating: <?php echo $fromCategory->tour->tourReviews ? $fromCategory->tour->tourReviews->count() : 0; ?>, starWidth: "15px", readOnly: true, ratedFill: "#ede811"});
                                                    });</script>
                                                </li>
                                                <li class="review-count">(<?php echo $fromCategory->tour->tourReviews ? $fromCategory->tour->tourReviews->count() : 0; ?>)</li>
                                            </ul>
                                            <p><?php //echo \Tourpage\Helpers\Utils::decodeString($review->reviewContent); ?></p>
                                        </div>
                                    </div>
                                    <?php //}?>
                                    <?php //}?>
                                    <?php } ?>
                                <?php } ?>

                        </div>
                    </div>
					
					<!-- weather forecast -->
					<?php echo $this->tag->javascriptInclude($this->url->getStatic(COMMON_DIR . "weather-plugin/jquery.simpleWeather.js")); ?>
					<div class="col-sm-4">
						<div class="tour-others">
							<div>
								<h4>Weather Forecast:</h4>
							</div>
							<div class="weather-forecast" style="border:1px solid rgb(204, 204, 204); padding: 7px !important;">
								<div id="weather"></div>
							</div>
						</div>
					</div>
			    </div>
            </div>
        </div><!-- /.row -->
    </div>
</section>

<script type="text/javascript">
	$(document).ready(function() {
		// get the current location using geolocation
		var lat = null;
		var long = null;
		/*
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(function (p) {
				lat = p.coords.latitude;
				long = p.coords.longitude;
				// get weather
				$.simpleWeather({
					//location: 'Mumbai',
					//zipcode: '2201200',
					//woeid: '',
					location: lat+','+long,
					//long: long,
					unit: 'c',
					success: function(weather) {
						var html = '';
						html = '<h2><i class="icon-'+weather.code+'"></i> '+weather.temp+'&deg;'+weather.units.temp+'</h2>';
						html += '<ul><li>'+weather.city+', '+weather.region+'</li>';
						html += '<li class="currently">'+weather.currently+'</li></ul>';
						//html += '<li>'+weather.wind.direction+' '+weather.wind.speed+' '+weather.units.speed+'</li></ul>';
						$("#weather").html(html);
						$(".weather-forecast").css({"background-image" : "url("+weather.image+")", "background-repeat": "no-repeat", "background-color" : "rgb(208, 218, 246)"});
					},
					error: function(error) {
						$("#weather").html('<p>'+error+'</p>');
					}
				});
			});
		} else {
			alert('Geo Location feature is not supported in this browser.');
		}*/
		// get weather
		$.simpleWeather({
			location: '<?php echo $member->addressOne; ?>',
			zipcode: '<?php echo $member->zipCode; ?>',
			unit: 'c',
			success: function(weather) {
				var html = '';
				html = '<h2><i class="icon-'+weather.code+'"></i> '+weather.temp+'&deg;'+weather.units.temp+'</h2>';
				html += '<ul><li>'+weather.city+', '+weather.region+'</li>';
				html += '<li class="currently">'+weather.currently+'</li></ul>';
				//html += '<li>'+weather.wind.direction+' '+weather.wind.speed+' '+weather.units.speed+'</li></ul>';
				$("#weather").html(html);
				$(".weather-forecast").css({"background-image" : "url("+weather.image+")", "background-repeat": "no-repeat", "background-color" : "rgb(208, 218, 246)"});
			},
			error: function(error) {
				$("#weather").html('<p>'+error+'</p>');
			}
		});
		
	});
    jQuery(function () {
        jQuery(".tours").each(function() {
            if(jQuery(this).is(':first-child')){
                var tourId = jQuery(this).attr("id");
                jQuery(".tours").css('border-bottom','0px')
                jQuery(".tour").hide();
				if(jQuery(".tour").hasClass("tour-"+tourId)){
                	jQuery(".tour-"+tourId).show();
					jQuery(".no-tour").css('display','none');
				} else {
					jQuery(".no-tour").css('display','block');
					jQuery(".no-tour").html("<h4>No Tour Found</h4>");
				}
				jQuery(this).css({"border-bottom": "solid 8px #1e769e", "color": "#1e769e"});   
                return false;
            }
        });
        jQuery(".tours").click(function() {
            var tourId = jQuery(this).attr("id");
            jQuery(".tours").css('border-bottom','0px')
            jQuery(".tour").hide();
            if(jQuery(".tour").hasClass("tour-"+tourId)){
                jQuery(".tour-"+tourId).show();
				jQuery(".no-tour").css('display','none');
			} else {
				jQuery(".no-tour").css('display','block');
				jQuery(".no-tour").html("<h4>No Tour Found</h4>");
			}
            jQuery(this).css({"border-bottom": "solid 8px #1e769e", "color": "#1e769e"});           
        });
    });
	
	
	
</script>

<script>
$(document).ready(function(){
    $("#btn1").click(function(){
        $("#form2").hide();
        $("#form1").show();
    });
    $("#btn2").click(function(){
        $("#form1").hide();
        $("#form2").show();
    });
});
</script>

<style>.error{border-color: #ff0000 !important;}.fav-opt{}.bg-info{margin-bottom: 10px;padding: 20px;}
    .tour-content{background:#ffffff;}

    .tour-options-content{background:#edf4f7;padding-bottom: 50px;}
    .tour-btn{margin: 40px 10px;}
    .nav-tabs {
        border-bottom: 0px;
    }
    .nav-tabs>li {
        padding: 10px 15px;
    }
    /*.nav-tabs>li>a {
        font-size: 20px;
        font-family: Arial;
        color: #333333;
        background: transparent;
        text-transform: uppercase;
        border: 0px;
        height: 51px;
        display: inline;
        padding: 10px 0px;
    }*/
	
	.nav-tabs>li>a {
		font-size: 100%;
		font-family: Arial;
		color: #333333;
		background: transparent;
		text-transform: uppercase;
		border: 0px;
		height: 51px;
		display: inline;
		padding: 0px 0px;
		line-height: 42px;
		margin: 0px;
		border-radius: 0px;
		font-weight: bold;
	}

    .nav-tabs>li>a:hover {
        border-color: transparent;
        border-bottom: solid 5px #1e769e;
    }
    .nav>li>a:focus, .nav>li>a:hover {
        text-decoration: none;
        background-color: transparent;;
    }
    /*.nav-tabs>li {
        width: 20%;
        text-align: center;
    }*/
	.nav-tabs>li {
		width: 20%;
		text-align: center;
		padding: 0px;
		padding-bottom: 1%;
	}
    .btn-all-tour {
        background: #888888;
        border-color: #888888;
        border-radius: 0px;
        padding: 10px 50px;
        text-decoration:none;
    }
    .btn-all-tour:hover {
        background: #777777;
        border-color: #777777;
        text-decoration:none;
    }
	
    .content-header .carousel {
        position: relative;
        height: 50px;
        width: 100%;
        clear: both;
    }
    .content-header .carousel-inner {
        position: relative;
        width: 100%;
        overflow: hidden;
        padding-left: 5%;
        padding-right: 5%;
    }
    .content-header .carousel-inner>.item {
        display: inline-block;
        width: 50px;
    }
    .content-header .carousel-control {
        width: 5%;
        color:#a3a3a3;
        text-shadow:none;
    }
    .content-header .carousel-control:focus, .carousel-control:hover {
        color: #aaaaaa;
    }
	.no-tour {
    	margin-top: 0px;
    	background-color: #ffffff;
    	border: 0px;
    	border-radius: 0px!important;
    	display: none;
	}
        
        #form1 .tour {
    padding: 0!important;
    border: 0!important;
    background: none!important;
    margin-top: 0!important;
   
        
        }  
        
</style>
<style>.tour {padding: 20px;border: 1px solid #ccc;background: #f9f9f9;margin-top: 20px;display:none;} .tours{line-height: 55px!important;}.tour-box{border-top: none;padding:0px;}.content-header > h1{margin-top: 5px;color: #1e769e;}.content-header > h1 a{color:#1e769e;text-decoration:none;font-size: 20px;font-weight:bold;}.content-header > h1 a:hover{color:#1f5f7a;}ul.review li.text-yellow{color: #ede811;}.content-header>ul.review{margin-top:10px;    margin-left: -5px;}ul.review li.review-count{color: #aaaaaa;margin-left:-5px;}
    .btn-book-tour {
        color: #fff;
        background: #1e769e;
        border-color: #1e769e;
        border-radius: 0px;
        text-align: center;
        text-decoration: none;
    }

    .btn-book-tour:hover {
        color: #fff;
        background: #1f5f7a;
        border-color: #1f5f7a;
        text-decoration: none;
    }
    .fav-tour {
        position: absolute;
        top: -20px;
        right: -20px;
        font-size: 25px;
        background: #eef1f2;
        padding: 5px;
    }
    ul.price li {
        font-size: 30px;
        color: #3e3f3f;
        font-weight: normal;
        font-family: Arial;
        line-height: 30px;
    }
    ul.price li.text-info-from {
        font-size: 16px;
        color: #aaaaaa;
        margin-top: 10%;
    }
    .input-group > .input-group-btn > button{
        border-radius: 0px;
        background: #1e769e;
        border-color: #1e769e;
    }
    .input-group > input{
        border-radius: 0px;
    }
    .text-22-sm > h4{
        color: #1f5f7a;
        font-weight: bold;
    }
    .text-22-sm p {
        padding-top: 10px;
    }
    ul.review {
        padding-top: 5px;
    }
    .tour-reviews,.tour-others{padding: 15px;}
    .tour-reviews > h4, .tour-others > h4{font-size: 20px;margin-top:20px;}
    .tit{border-bottom:0px;}
    .tit > a{font-size:18px;color:#1e769e;text-decoration:none;}
    .tit > a:hover,.ven a:hover{color:#1f5f7a;text-decoration:none;}
    
    .h60 {font-size: 50px;margin-left: 35%;}
</style>
<script>
    function redirectToSpecificPage(url, id, type) {
    	var mapForm = document.createElement("form");
    	mapForm.method = "POST";
    	mapForm.action = url;

    	var mapInput = document.createElement("input");
    	mapInput.type = "hidden";
    	mapInput.name = type;
    	mapInput.value = id;
    	mapForm.appendChild(mapInput);

    	document.body.appendChild(mapForm);
    	map = window.open(url, "_self");
    	if (map) {
            mapForm.submit();
    	}
    }
</script>