<!-- DYNAMIC BANNER IMAGES BEGIN -->
    <!-- @author Algie Caballes -->
    <header class="header">
        <div class="s-banner">
            <div class="banner-caption">
                <!--<h1>Book tickets for top attractions around the world</h1>-->
            </div>
            <div id="transition-timer-carousel" class="carousel slide transition-timer-carousel" data-ride="carousel">
                <div class="carousel-inner">
                    <!-- banner images display -->
                    <?php if ($bannerImages->count() > 0): ?>
                        <?php foreach ($bannerImages as $key => $banner): ?>
                            <div class="item <?php if ($key == 0) { echo 'active'; } ?>">
                                <a href="<?php echo $banner->bannerLink; ?>" target="_blank"><img src="<?php echo $banner->getBannerUri(); ?>" alt=""style="width:100%; "/></a>
                                <div class="carousel-caption">
                                    <div class="carousel-caption" style="top: 0; bottom: 0;">
                                        <h1><?php echo $banner->bannerCaption; ?></h1>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="item">
                            <img src="<?php echo $this->url->getStatic(FRONT_END_DIR . 'images/banner-img.png'); ?>"/> 
                        </div>
                    <?php endif; ?>
                </div>
            </div>   
        </div>
    </header>

<section class="tour-content">
    <div class="container">
        <div style="margin-top: 20px !important; margin-bottom: 20px !important;">
            <?php echo $pageContent; ?>
        </div>
    </div>
</section>