    <?php echo $this->tag->stylesheetLink($this->url->getStatic(COMMON_DIR . "css/slimNav_sk78.css")); ?>
    <?php echo $this->tag->stylesheetLink($this->url->getStatic(COMMON_DIR . "css/colorbox.css")); ?>
<div class="container">
<!--  ---------------------------------cut-here-----------------------------  --->
<div class="gallery-sec">
    <h1>Gallery</h1>
    <ul>
        <?php foreach ($gallery['images']['image'] as $key => $item): ?>
            <?php if ($gallery['images']['isShown'][$key]): ?>
                <li>
                    <div class="image-holder">
                        <a class="group1" href="<?php echo $item; ?>" title="<span><?php echo $members[$gallery['images']['memberId'][$key]]['name']; ?></span> / <?php echo $gallery['images']['date_uploaded'][$key]; ?>">
                            <img style="max-width:100%; height:auto;" src="<?php echo $item; ?>" alt="img1" />
                        </a>
                    </div>
                    <div class="text-holder">
                        <div><span><?php echo $gallery['images']['tourname'][$key]; ?></span></div>
                        <hr>
                        <p><span><?php echo $members[$gallery['images']['memberId'][$key]]['email']; ?></span> / <span><?php echo $members[$gallery['images']['memberId'][$key]]['name']; ?></span> / <?php echo $gallery['images']['date_uploaded'][$key]; ?></p>
                    </div>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <div class="clearfix" style="margin-bottom:20px;"></div>
</div>
<?php echo $this->tag->javascriptInclude($this->url->getStatic(COMMON_DIR . "js/jquery.colorbox.js")); ?>
<script>
    $(document).ready(function(){
        //Examples of how to assign the Colorbox event to elements
        $(".group1").colorbox({rel:'group1'});
    });
</script>