<?php /*?><?php
$address = '112 W 42nd st,New York,NY,10021';
$location = \Tourpage\Helpers\Utils::getGeolocation($address);
$infowindowContent = '<div style="width:220px;height:120px;">';
$infowindowContent .= '<a href="'.$this->url->getBaseUri().'"><img style="height: 50px;" src="'.$this->url->getStatic(FRONT_END_DIR . 'images/logo_home.jpg').'"/></a><br/><br/>';
$infowindowContent .= '<i class="fa fa-building"></i> 112 42nd street New York NY 1121<br/>';
$infowindowContent .= '<i class="fa fa-phone"></i> +12 1234 1212 / 215 454 4455<br/>';
$infowindowContent .= '<i class="fa fa-envelope"></i> info@tourpage.net';
$infowindowContent .= '</div>';
?>
<div id="map" style="width:100%;height:350px;margin-top: 20px;"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQc2RC2E2C7SgUoML9D-Q-VMUt7Q6fEhA"></script>
<script type="text/javascript">
	function initializeMap() {
		var mapCenter = {
			lat : <?php echo $location->lat;?>,
			lng : <?php echo $location->lng . "\n";?>
		};
		var mapOptions = {
			zoom: 15,
			scrollwheel: false,
			center: new google.maps.LatLng(mapCenter.lat, mapCenter.lng),
			overviewMapControl: true,
			overviewMapControlOptions: {
				opened: true,
			},
		};
		var map = new google.maps.Map(document.getElementById('map'),mapOptions);
		var infowindow = new google.maps.InfoWindow({
			maxWidth: 500
		});
		var marker = new google.maps.Marker({
			position: new google.maps.LatLng(mapCenter.lat, mapCenter.lng),
			map: map,
		});
		google.maps.event.addListener(marker, 'click', (function(marker) {
			return function() {
				infowindow.setContent('<?php echo $infowindowContent;?>');
				infowindow.open(map, marker);
			}
		})(marker));
	}
	google.maps.event.addDomListener(window, 'load', initializeMap);
</script><?php */?>

