
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>tourpage</title>

    <!-- Bootstrap core CSS -->
    <link href="../elements/supplier/css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="../elements/supplier/css/style.css" rel="stylesheet" />
   
   
  
    <link href="../elements/supplier/font-awesome/css/font-awesome.min.css" rel="stylesheet">
     <link href="../elements/supplier/css/slimNav_sk78.css" rel="stylesheet" />
	
  
</head>
