<div class="layout sidebar">
    <ol>
        <li><a href="<?php echo $this->url->get('/account'); ?>"><i class="glyphicon glyphicon-user"></i> Profile</a></li>
        <li><a href="<?php echo $this->url->get('/account/paymentoptions'); ?>"><i class="glyphicon glyphicon-credit-card"></i> Payment Options</a></li>
        <li><a href="<?php echo $this->url->get('/account/settings'); ?>"><i class="glyphicon glyphicon-cog"></i> Settings </a></li>
        <li><a href="<?php echo $this->url->get('/account/changepass'); ?>"><i class="glyphicon glyphicon-lock"></i> Change Password</a></li>
    </ol>
</div>
