<div class="layout sidebar">
    <ol>
        <li><a href="<?php echo $this->url->get('/account/reviews/confirmed'); ?>"><i class="glyphicon glyphicon-sunglasses"></i>Confirmed review</a></li>
        <li><a href="<?php echo $this->url->get('/account/reviews/pending'); ?>"><i class="glyphicon glyphicon-pencil"></i> Pending review</a></li>
        <li><a href="<?php echo $this->url->get('/account/reviews/new'); ?>"><i class="glyphicon glyphicon-plus"></i> Add new review</a></li>
    </ol>
</div>
