<div class="layout sidebar">
    <ol>
        <li><a href="<?php echo $this->url->get('/account/travelpreference/perfectday'); ?>"><i class="glyphicon glyphicon-music"></i> Your Perfect Day</a></li>
        <li><a href="<?php echo $this->url->get('/account/travelpreference/fevactivities'); ?>"><i class="glyphicon glyphicon-plane"></i> Favorite Type of Activities</a></li>
        <li><a href="<?php echo $this->url->get('/account/travelpreference/fevdestination'); ?>"><i class="glyphicon glyphicon-plane"></i> Favorite Destination</a></li>
    </ol>
</div>
