<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-th-list"></span> Categories <span class="badge"><?php echo count($categoryCount); ?></span>
            <div class="pull-right">
                <a class="btn btn-danger btn-xs tooltips" href="<?php echo $this->url->get('/admin/tours/addcategory'); ?>" role="button" title="Add new tour category">
                    <span class="glyphicon glyphicon-plus"></span> New Category
                </a>
            </div>
        </h3>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($pager->getTotalItems() > 0) { ?>
                        <?php foreach ($pager->getItems() as $item) { ?>
                            <tr>
                                <td><?php echo $item->categoryTitle; ?></td>
                                <td><?php echo $item->getStatus(); ?></td>
                                <td>
                                    <?php echo $this->tag->linkTo(array('/admin/tours/managecategory/edit/' . $item->categoryId, '<span class="glyphicon glyphicon-pencil"></span>', 'class' => 'btn btn-primary btn-xs tooltips', 'title' => 'Edit Category')); ?>
                                    <?php echo $this->tag->linkTo(array('/admin/tours/managecategory/remove/' . $item->categoryId, '<span class="glyphicon glyphicon-trash"></span>', 'class' => 'btn btn-danger btn-xs tooltips', 'title' => 'Remove Category')); ?>
                                </td>
                            </tr>
                            <?php if($item->getChilds()){?>
                            <?php foreach ($item->getChilds() as $child) { ?>
                            <tr>
                                <td><?php echo $item->categoryTitle. ' <span class="glyphicon glyphicon-chevron-right"></span> ' . $child->categoryTitle; ?></td>
                                <td><?php echo $child->getStatus(); ?></td>
                                <td>
                                    <?php echo $this->tag->linkTo(array('/admin/tours/managecategory/edit/' . $child->categoryId, '<span class="glyphicon glyphicon-pencil"></span>', 'class' => 'btn btn-primary btn-xs tooltips', 'title' => 'Edit Category')); ?>
                                    <?php echo $this->tag->linkTo(array('/admin/tours/managecategory/remove/' . $child->categoryId, '<span class="glyphicon glyphicon-trash"></span>', 'class' => 'btn btn-danger btn-xs tooltips', 'title' => 'Remove Category')); ?>
                                </td>
                            </tr>
                            <?php }?>
                            <?php }?>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="3" class="text-center">No category is here</td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<nav>
    <?php echo $pager->getLinks(); ?>
</nav>


