<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-<?php echo $formType == 'new' ? 'plus' : 'pencil'; ?>"></span> <?php echo $formType == 'new' ? 'New Description Fields' : 'Update Description Fields'; ?>
        </h3>
    </div>
    <div class="panel-body">
        <form class="form-control-static" method="post">
            <div class="tab-wrapper">
                <div class="col-xs-6 no-pad-left">
                    <?php $form->renderHorizental('key_name'); ?>
                    <?php $form->renderHorizental('key_status'); ?>
                </div>
            </div>
            <div class="col-lg-12 no-pad">
                <?php echo $form->render('submit'); ?>
                <?php echo $this->tag->linkTo(array('/admin/tours/descfields', 'Back', 'class' => 'btn btn-info')); ?>
            </div>
        </form>
    </div>
</div>
