<div style="margin-bottom: 10px;">
    <h4>Filter Tours</h4>
    <form class="form-inline" method="post">
        <div class="form-group">
            <?php
            echo Phalcon\Tag::textField(array(
                "tn",
                "class" => "form-control",
                "placeholder" => "By Tour Title",
            ));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo Phalcon\Tag::select(array(
                "to",
                $vendors,
                "useEmpty" => true,
                "emptyText" => "All Operator",
                'emptyValue' => "[all]",
                "using" => array("vendorId", "businessName"),
                "class" => "form-control"
            ));
            ?>
        </div>
        <?php /*<div class="form-group">
            <?php
            echo Phalcon\Tag::selectStatic(array(
                "bs",
                "useEmpty" => true,
                "emptyText" => "All Booking Status",
                'emptyValue' => "[all]",
                array(
                    \Tourpage\Models\Tours::BOOKING_OPEN_STATUS_CODE => 'Open',
                    \Tourpage\Models\Tours::BOOKING_UPCOMMING_STATUS_CODE => 'Up Comming',
                    \Tourpage\Models\Tours::BOOKING_CLOSE_STATUS_CODE => 'Close',
                ),
                "class" => "form-control"
            ));
            ?>
        </div>*/ ?>
        <div class="form-group">
            <?php
            echo Phalcon\Tag::selectStatic(array(
                "s",
                "useEmpty" => true,
                "emptyText" => "All Status",
                'emptyValue' => "[all]",
                array(
                    \Tourpage\Models\Tours::ACTIVE_STATUS_CODE => 'Active',
                    \Tourpage\Models\Tours::INACTIVE_STATUS_CODE => 'Inactive',
                ),
                "class" => "form-control"
            ));
            ?>
        </div>
        <button type="submit" class="btn btn-danger">Filter</button>
        <?php if (count($defaultValues) > 0) { ?>
            <?php echo $this->tag->linkTo("/admin/tours", "Clear"); ?>
        <?php } ?>
    </form>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-th-list"></span> Tours <span class="badge"><?php echo $pager->getTotalItems(); ?></span>
        </h3>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Tour Title</th>
                        <th>Reviews</th>
                        <th>Rating</th>
                        <th>Store Front</th>
                        <th>Price</th>
                        <th>Booking</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($pager->getTotalItems() > 0) { ?>
                        <?php foreach ($pager->getItems() as $item) { ?>
                            <tr>
                                <td><?php echo $this->tag->linkTo(array($item->getUri(), $item->tourTitle, 'local' => false, 'target' => '_blank')); ?></td>
                                <td>
									<a href="<?php echo $this->url->get('/admin/tours/reviews/1/' . $item->tourId);?>"><?php echo $item->tourReviews ? $item->tourReviews->count() : 0;?> Reviews</a>
                                </td>
                                <td>
									<div id="star-rate-<?php echo $item->tourId;?>"></div>
									<script>jQuery(function(){jQuery('#star-rate-<?php echo $item->tourId;?>').rateYo({rating: <?php echo $item->tourRating ? $item->tourRating->getStar() : 0;?>,starWidth: "20px",readOnly: true});});</script>
                                </td>
                                <td>
									<?php if($item->tourVendor != null && $item->tourVendor->vendor != null): ?>
										<?php echo $this->tag->linkTo(array($item->tourVendor->vendor->getStorFrontUri(), $item->tourVendor->vendor->businessName, 'local' => false, 'target' => '_blank')); ?>
									<?php endif; ?>
								</td>
                                <td><?php echo \Tourpage\Helpers\Utils::formatCurrency($item->tourPrice->getPrice()); ?></td>
                                <td><?php echo $item->isBookingActive() ? '<span class="label label-success">Available</span>' : '<span class="label label-warning">Close</span>'; ?></td>
                                <td>
                                    <?php echo $this->tag->linkTo(array('/admin/tours/edit/' . $item->tourId, '<span class="glyphicon glyphicon-pencil"></span>', 'class' => 'btn btn-primary btn-xs tooltips', 'title' => 'Edit Tour')); ?>
                                    <?php echo $this->tag->linkTo(array('/admin/tours/remove/' . $item->tourId, '<span class="glyphicon glyphicon-trash"></span>', 'class' => 'btn btn-danger btn-xs tooltips', 'title' => 'Remove Tour')); ?>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="9" class="text-center">No tours is here</td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>

</div>
<nav>
    <?php echo $pager->getLinks(); ?>
</nav>


