<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-remove"></span> Remove Description Fields
        </h3>
    </div>
    <div class="panel-body">
        <div class="page-header">
            <h2>Are you sure! you want to remove <small><i>"<?php echo $attributeKey->keyName; ?>"</i></small> ?</h2>
        </div>
        <form method="post">
            <input type="hidden" name="key" value="<?php echo md5('confirm'); ?>" />
            <input type="hidden" name="key_id" value="<?php echo $attributeKey->keyId; ?>" />
            <input type="submit" name="submit" class="btn btn-danger" value="Remove" />
            <?php echo $this->tag->linkTo(array('/admin/tours/descfields', 'Back', 'class' => 'btn btn-primary')); ?>
        </form>
    </div>
</div>
