<body>
<!--  ---------------------------------header-----------------------------  --->
<div class="section header">
<div class="container">
<div class="row">
<div class="col-lg-3 col-md-3 col-sm-3">
<div class="sitelogo">
<a href="Supplier_home.html"><img style="max-width:100%; height:auto;" src="../elements/supplier/images/main-logo.png" alt="site-logo" /></a>
</div>
</div>
<!--  ---------------------------------nav-----------------------------  --->

<div class="col-lg-6 col-md-6 col-sm-3">
<div class="menu-section">
<nav>
<ul>
<li><a class="" href="#">Features</a></li>
<li><a href="Supplier_pricing.html">Pricing</a></li>
<li><a href="#">News</a></li>
<li><a href="#">Support</a></li>
<div class="clear"></div>
</ul>
</nav>
</div>
</div>

<div class="col-lg-3 col-md-3 col-sm-3">
<div class="login-sec">
<ul>
<li><a class="sup_login" href="<?php echo $this->url->get('/public/auth/login'); ?>">login</a></li>
<li><a class="sup_register" href="<?php echo $this->url->get('/public/auth/register'); ?>">Get Started Today</a></li>

</ul>
<div class="clear"></div>
</div>

</div>


</div>
</div>
</div>

<!-------------------------------------banner----------------------->
<section class="banner-sec">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/banner1.jpg" alt="banner" />
<div class="banner-caption">
<h1>Build Your Own Tour Store with Easy Booking and Calendar</h1>
<p>Complete Tour Operator Solution with Your Own Store Front and Booking</p>

<div class="banner-btn">
<ul>
<li><a class="sup_register b-pading b-color" href="#">Watch the Video</a></li>
<li><a class="sup_register b-pading" href="#">Get Started Today</a></li>
</ul>
</div>
</div>
</section>

<!-------------------------------------ferture-sec----------------------->
<section class="feature-sec">
<div class="container">
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12">
<div class="feature-contant">
<h1>Features</h1>
<h3>Product Snapshot</h3>
<p>similique reprimique mel no. Vim enim nonumes albucius ea, cibo apeirian cotidieque nec no, id duo eruditi saperet. Adhuc gloriatur his at, ea eam postulant intellegebat. Reque intellegam ea pro, ad sea vero meis menandri. Ea sea magna pericula, virtute consequat signiferumque quo an.</p>
<p>
<span>Ei amet expetenda usu. Ut nec libris conceptam complectitur</span><br />
id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim.
</p>

<div class="feature-contant-blog">
<ul>
<li>
<div class="feature-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/fe-img1.jpg" alt="img" />
</div>
<div class="feature-blog-heading">
<h1>Ei amet expetenda usu amet </h1>
</div>
<div class="feature-blog-contant">
<p>id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vimtrum eligendi cum ne, at viris dicunt dolores. </p>
</div>
</li>

<li>
<div class="feature-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/fe-img2.jpg" alt="img" />
</div>
<div class="feature-blog-heading">
<h1>Ei amet expetenda usu amet </h1>
</div>
<div class="feature-blog-contant">
<p>id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vimtrum eligendi cum ne, at viris dicunt dolores. </p>
</div>
</li>

<li>
<div class="feature-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/fe-img3.jpg" alt="img" />
</div>
<div class="feature-blog-heading">
<h1>Ei amet expetenda usu amet </h1>
</div>
<div class="feature-blog-contant">
<p>id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vimtrum eligendi cum ne, at viris dicunt dolores. </p>
</div>
</li>

<li>
<div class="feature-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/fe-img4.jpg" alt="img" />
</div>
<div class="feature-blog-heading">
<h1>Ei amet expetenda usu amet </h1>
</div>
<div class="feature-blog-contant">
<p>id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vimtrum eligendi cum ne, at viris dicunt dolores. </p>
</div>
</li>

</ul>

</div>

<div class="feature-contant-btn">
<a class="sup_register b-pading" href="#">Get Started Today</a>
</div>


<div class="clear"></div>
</div>

<div class="feature-contant">
<h3>Feature Listing</h3>
<img class="pull-right" style="max-width:100%; height:auto;" src="../elements/supplier/images/feature-listing.jpg" alt="img" />
<p>similique reprimique mel no. Vim enim nonumes albucius ea, cibo apeirian cotidieque nec no, id duo eruditi saperet. Adhuc gloriatur his at, ea eam postulant intellegebat. Reque intellegam ea pro, ad sea vero meis menandri. Ea sea magna pericula, virtute consequat signiferumque quo an.
</p>
<p><span>Ei amet expetenda usu. Ut nec libris conceptam complectitur</span><br />
id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim.</p>
<div class="clear"></div>
</div>

<div class="feature-contant">
<h3>Benefits</h3>
<p>similique reprimique mel no. Vim enim nonumes albucius ea, cibo apeirian cotidieque nec no, id duo eruditi saperet. Adhuc gloriatur his at, ea eam postulant intellegebat. Reque intellegam ea pro, ad sea vero meis menandri. Ea sea magna pericula, virtute consequat signiferumque quo an.
</p>

<p>
<span>Ei amet expetenda usu. Ut nec libris conceptam complectitur</span><br />
id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim.
</p>
<p>
<span>Ei amet expetenda usu. Ut nec libris conceptam complectitur</span><br />
id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim. id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro no animal denique nominavi. Et mea primis prompta, nostrum eligendi cum ne, at viris dicunt dolores vim.
</p>

<div class="feature-contant-btn">
<a class="sup_register b-pading" href="#">Get Started Today</a>
</div>

<div class="clear"></div>
</div>

<div class="feature-contant no-border">
<h3>Testimonial</h3>
<div class="testimonial-heading">
“TourPage integrated secure booking system has streamlined the booking process for both us and our guests.”
<div class="testimonial-heading-bg"></div>
</div>

<div class="feature-contant-blog">
<ul>
<li>
<div class="feature-blog-img">
<img style="max-width:100%; height:auto; border-radius: 100%;" src="../elements/supplier/images/testimonial-img1.png" alt="img" />
</div>
<div class="feature-blog-heading">
<h2>First, Last Name</h2>
<h2><span>Store Name, City, State</span></h2>

</div>


</li>

<li>
<div class="feature-blog-img">
<img class="testimonial-active" style="max-width:100%; height:auto;border-radius: 100%;" src="../elements/supplier/images/testimonial-img2.png" alt="img" />
</div>
<div class="feature-blog-heading">
<h2>First, Last Name</h2>
<h2><span>Store Name, City, State</span></h2>

</div>


</li>

<li>
<div class="feature-blog-img">
<img style="max-width:100%; height:auto; border-radius: 100%;" src="../elements/supplier/images/testimonial-img3.png" alt="img" />
</div>
<div class="feature-blog-heading">
<h2>First, Last Name</h2>
<h2><span>Store Name, City, State</span></h2>

</div>


</li>

<li>
<div class="feature-blog-img">
<img style="max-width:100%; height:auto; border-radius: 100%;" src="../elements/supplier/images/testimonial-img4.png" alt="img" />
</div>
<div class="feature-blog-heading">
<h2>First, Last Name</h2>
<h2><span>Store Name, City, State</span></h2>

</div>


</li>

</ul>



</div>



</div>


</div>

</div>
</div>

</section>

<!-------------------------------------blog-sec----------------------->

<section class="supply-blog">
<div class="container">
<div class="row">
<h1>NEWS</h1>
<div class="col-lg-12 col-md-12 col-sm-12">
<div class="supply-blog-holder">
<div class="supply-blog-text">
<p>Ei amet expetenda usu. Ut nec libris conceptam complectitur id tollit menandri disputationi has. Ex omittam accusata honestatis mea, pro </p>
<p><span>July 27, 2016</span></p>
</div>

<div class="supply-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/sup-blog-img1.jpg" alt="img" />
</div>

<div class="clear"></div>
</div>


</div>


<div class="col-lg-6 col-md-6 col-sm-6">
<div class="supply-blog-holder">
<div class="supply-blog-text">
<p>Ei amet expetenda usu. Ut nec libris conceptam complectitur id tollit menandri disputationi has.</p>
<p><span>July 27, 2016</span></p>
</div>

<div class="supply-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/sup-blog-img2.jpg" alt="img" />
</div>

<div class="clear"></div>
</div>


</div>

<div class="col-lg-6 col-md-6 col-sm-6">
<div class="supply-blog-holder">
<div class="supply-blog-text">
<p>Ei amet expetenda usu. Ut nec libris conceptam complectitur id tollit menandri disputationi has.</p>
<p><span>July 27, 2016</span></p>
</div>

<div class="supply-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/sup-blog-img3.jpg" alt="img" />
</div>

<div class="clear"></div>
</div>


</div>

<div class="col-lg-6 col-md-6 col-sm-6">
<div class="supply-blog-holder">
<div class="supply-blog-text">
<p>Ei amet expetenda usu. Ut nec libris conceptam complectitur id tollit menandri disputationi has.</p>
<p><span>July 27, 2016</span></p>
</div>

<div class="supply-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/sup-blog-img4.jpg" alt="img" />
</div>

<div class="clear"></div>
</div>


</div>

<div class="col-lg-6 col-md-6 col-sm-6">
<div class="supply-blog-holder">
<div class="supply-blog-text">
<p>Ei amet expetenda usu. Ut nec libris conceptam complectitur id tollit menandri disputationi has.</p>
<p><span>July 27, 2016</span></p>
</div>

<div class="supply-blog-img">
<img style="max-width:100%; height:auto;" src="../elements/supplier/images/sup-blog-img5.jpg" alt="img" />
</div>

<div class="clear"></div>
</div>


</div>

<div class="clear"></div>

<div class="pagination-area">
<ul class="pagination">
              <li class="disabled"><a href="#">«</a></li>
              <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#">»</a></li>
            </ul>

</div>

</div>

</div>


</section>

<!------------------------------------footer----------------------------->

<section class="footer">
<div class="container">
<div class="row">
<div class="col-lg-4 col-md-4 col-sm-4">
<div class="footer-holder1">
<ul>
<li><a href="#"><img src="../elements/supplier/images/footer-icon1.png" alt="icon" /></a></li>
<li><a href="#"><img src="../elements/supplier/images/footer-icon2.png" alt="icon" /></a></li>
<li><a href="#"><img src="../elements/supplier/images/footer-icon3.png" alt="icon" /></a></li>
</ul>

</div>

</div>

<div class="col-lg-4 col-md-4 col-sm-4">
<div class="footer-holder2">
<ul>
<li><a href="#">About Tourpage</a></li>
<li><a href="#">Careers	</a></li>
<li><a href="#">Privacy, Terms & Condition</a></li>

</ul>
</div>

</div>

<div class="col-lg-4 col-md-4 col-sm-4">
<div class="footer-holder2">
<ul>
<li><a href="#">Mobile Solution</a></li>
<li><a href="#">FAQ</a></li>
<li><a href="#">Support & Documentation</a></li>

</ul>
</div>

</div>

<div class="clear"></div>
<div class="footer-bottom">
Copyright © Tourpage 2016, All rights reserved
</div>


</div>
</div>
</section>



<!------------------------------------footer---------------------------------->
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="../elements/common/js/bootstrap.js"></script>
    <script src="../elements/common/js/jquery.colorbox.js"></script>

<!------------------------------------nav---------------------------------->    
     
	<script src="../elements/common/js/jquery.slimNav_sk78.min.js"></script>
	
	<script>
	jQuery(document).ready(function($) {
		jQuery('nav ').slimNav_sk78();
	});
	</script>
 <!------------------------------------banner---------------------------------->      
  <script>
		$(function() {
		
			$("#slideshow > div:gt(0)").hide();
	
			setInterval(function() { 
			  $('#slideshow > div:first')
			    .fadeOut(1000)
			    .next()
			    .fadeIn(1000)
			    .end()
			    .appendTo('#slideshow');
			},  3000);
			
		});
	</script>  
    
</body>
<style>
    html, body {
  height: 100%;
}

.img-home-portfolio,
.img-customer,
.portfolio-item {
  margin-bottom: 30px;
}

.tab-pane {
  margin-top: 15px;
}

/* Page Sections */


*{margin:0; padding:0;}

body{margin:0; padding:0;  font-family:Arial, Helvetica, sans-serif; background:#fff;
	

	 }

div, h1, h2, h3, h4, h5, h6, p, tr, td{margin:0; padding:0;}

ul{list-style-type:none; margin:0; padding:0;}
img{border:0; margin:0; padding:0;}
a{outline:none; text-decoration:none;}

form, fieldset{background:none; border:none; margin:0; padding:0;}

header, nav, section, article, aside, footer {
   display:block;
}

.clear{clear:both;}

/***************************************header***************************************/
.header{background:#044467; padding:10px 0;}
.sitelogo{}
.sitelogo a{outline:none;}


@media only screen and (min-width:970px){
/**************************nav*************************************/
.menu-section{padding:20px 0 0; text-align:center; }
.menu-section ul{margin:0; padding:0;  padding-bottom:1px;}
.menu-section ul li{display:inline-block;}
.menu-section ul li:last-child{}
.menu-section ul li a{color:#fff; font-size:16px; text-transform:uppercase; text-decoration:none; outline:none; line-height:15px; padding: 15px 25px ;}
.menu-section ul li a:hover, .active{ color:#ccc !important; text-decoration:none; outline:none; }

/**************************sub-menu*************************************/
.menu-section ul ul {
    padding:0;
    margin: 0;
	z-index:9999; background:#b7b7b7; transition: all 200ms linear 0s;  width:250px; color:#fff; top:39px;} 


.menu-sectionul ul li {
    list-style-type: none;
    display:block; float:none;
	width:250px;
	border:none;
	
	
}

.menu-section ul ul li a {
    text-decoration: none;
    color:#fff;
   	padding:10px 20px;
    display:inline-block;
	line-height:0!important;
	width:250px;
	line-height: 20px!important;
	font-size:15px;
	border:none;
	text-transform:none;

}

.menu-section ul ul li a:hover{ color:#fff; border:none; width:250px;}

.menu-section li ul {
    display:none!important;
    position: absolute;
    
}
.menu-section li:hover ul {
    display:block!important;
}
}
/**************************nav-end***************************************/
.login-sec{text-align:right; margin-top:18px;}

.login-sec ul li{display:inline-block; margin-left:10px;}
.sup_login{border:1px solid #fff; font-size:16px; text-transform:uppercase; padding:6px 10px; outline:none;
	 text-decoration:none; color:#fff;}
.sup_login:hover{color:#ccc; text-decoration:none; outline: none;}

.sup_register{font-size:16px; padding:6px 10px; outline:none; text-decoration:none; color:#fff; background:#f08f25;}

.sup_register:hover {color:#ccc; text-decoration:none; outline: none;}
.sup_register:focus{color:#ccc; text-decoration:none; outline: none;}
.sup_register a:active{color:#ccc; text-decoration:none; outline: none;}
.login-sec ul li a:active{color:#ccc; text-decoration:none; outline: none;}
/**************************banner***************************************/
.banner-sec{margin-bottom:20px; position:relative;}
.banner-caption{position:absolute; width:47%; left:20%; top:32%;}
.banner-caption h1{font-size:45px; color:#fff; line-height:45px; margin-bottom:10px;}
.banner-caption p{font-size:14px; color:#fff;  margin-bottom:10px;}

.banner-btn{text-align:right; margin-top:60px; margin-right:10%;}
.banner-btn ul li{list-style:none; display:inline-block; margin-left:10px;}
.b-color{background:#044467;}
.b-pading{padding:10px 15px; font-size:20px;}
/**************************feature***************************************/
.feature-sec{margin:30px 0;}
.feature-contant{border-bottom:1px solid #ccc; padding-bottom:20px; margin:20px 0;}
.feature-contant h1{font-size:36px; color:#044467; text-transform:uppercase; margin-bottom:20px; text-align:center;}
.feature-contant h3{font-size:26px; color:#191919;  margin-bottom:20px; }
.feature-contant p{font-size:16px; color:#191919;  margin-bottom:20px; text-align:justify; }
.feature-contant p span{font-weight:bold;}

.feature-contant-blog{margin-top:20px;}

.feature-contant-blog ul li{list-style:none; width:23.5%; margin:0 .5%; display:inline-block; text-align:center;}
.feature-blog-img{margin-bottom:30px;}
.feature-blog-heading{margin:20px 0;}
.feature-blog-heading h1{ color:#044467; font-size:17px; font-weight:bold; text-align:center;}
.feature-blog-heading h2{ color:#044467; font-size:17px;  text-align:center; margin-bottom:10px;}
.feature-blog-heading h2 span{ color:#191919;}
.feature-blog-contant{margin:10px 0 0;}
.feature-blog-contant p{color:#191919; font-size:16px; line-height:20px; text-align:center;}
.feature-contant-btn{text-align:center; margin:20px 0;}
.no-border{border:0;}
.testimonial-heading{background:#95bf15; color:#fff; font-size:25px; padding:20px; width:76%;
 margin:20px auto; position:relative;}
.testimonial-heading-bg{position:absolute; bottom:-14px; left:30%; background:url(../elements/supplier/images/testimonial-header-bg.png) no-repeat;
	width:35px; height:17px;}
.testimonial-active{border:3px solid #95bf15;}

.supply-blog{ margin:20px 0 40px;}
.supply-blog h1{font-size:36px; color:#044467; text-transform:uppercase; margin-bottom:20px; text-align:center;}
.supply-blog-holder{margin:10px 0;}
.supply-blog-holder .supply-blog-text{background:#f3f3f3; padding:10px;}
.supply-blog-holder .supply-blog-text p{color:#141414; font-size:14px; }
.supply-blog-holder .supply-blog-text p span{color:#6e6e6e; font-size:14px;}
.supply-blog-holder .supply-blog-img{}
.pagination-area{  text-align:center; margin:40px 0;}	
.pagination>li>a, .pagination>li>span {margin: 0 5px;}
.pagination-area ul li{padding:0; border-bottom:none;}
.pagination > li > a, .pagination > li > span{color:#ccc;}
.pagination > .active > a, .pagination > .active > span, .pagination > .active > a:hover, .pagination > .active > span:hover, .pagination > .active > a:focus, .pagination > .active > span:focus{background-color:#fff; color:#000; border-color:#ccc;}
/**************************footer****************************/
.footer{margin-top:50px; background:#044467; padding:50px 0;}
.footer-holder1{}
.footer-holder1 ul li{list-style:none; display:inline-block; margin-right:10px;}

.footer-holder2{}
.footer-holder2 ul li{list-style:none; margin:10px 0; font-size:14px;}
.footer-holder2 ul li a{text-decoration:none; outline:none; color:#fff;}
.footer-holder2 ul li a:hover{text-decoration:none; outline:none; color:#ccc;}

.footer-bottom{margin-top:30px; font-size:12px; color:#fff; text-align:center;}

/********************************pricing-page**********************************/
.pricing-banner{}

.pricing-banner .banner-caption{ width:47%; left:40%; top:15%;}
.pricing-banner .banner-caption h1{font-size:30px; color:#044467;  margin-bottom:10px; border-bottom:1px solid #fff; padding-bottom:5px; width:85%;}
.pricing-banner .banner-caption p{font-size:14px; color:#fff;  margin-bottom:10px; font-style:italic;}

.pricing-banner .banner-btn{text-align:right; margin-top:30px; margin-right:10%;}

.pricing-blog{margin:20px 0;}

.pricing-blog ul li{list-style:none; display:inline-block; width:20%; margin:0 2%; background:#f4f3f3;}

.pricing-blog-top{background:#366985; padding:50px 0; text-align:center; position:relative;}
.blog-active{background:#044467;}
.most-popular{position:absolute; left:0; top:0; width:74px; height:80px;}
.pricing-blog-top h3{font-size:22px; color:#fff; margin-bottom:20px;}
.pricing-blog-top h1{font-size:60px; color:#fff; font-weight:bold;}
.pricing-blog-top h1 span{font-size:30px; font-weight:normal;}

.pricing-blog-bottom{margin-top:20px; padding:0 10px;}
.pricing-blog-bottom p{ margin:20px 0;}

.pricing-blog-bottom p img{float:left; margin-right:20px;}

.pricing-tabel{margin:40px 0 80px; background:#ecf0f1; position:relative;}

.pricing-tabel-header{background:#2f6a8b; padding:5px 0; font-size:18px; text-transform:uppercase; color:#fff; font-weight:bold;}
.pricing-tabel-header ul li{list-style:none; display:inline-block; width:20%; text-align:center;}
.pricing-tabel-header ul li:nth-child(1){text-align:left; padding-left:20px; width:18%;}


.pricing-tabel-data-header{}

.pricing-tabel-data-header h5{font-size:18px; text-transform:uppercase; color:#2f6a8b; font-weight:bold;
 padding:5px 0 5px 20px; width:18%;}
 
.pricing-tabel-data{border-bottom:1px solid #c3c2c2;}
 
.pricing-tabel-data ul li{list-style:none; float:left;  width:19.8%; text-align:center;
 font-size:14px; color:#2f6a8b; padding:5px 0; background:#fff; margin:0 0.8px; }
.pricing-tabel-data ul li:nth-child(1){text-align:left; padding-left:20px; width:20%; color:#fff; background:#2f6a8b;} 
 
 .pricing-table-m-popular{width:101px; height:51px; top:0; right:18%;
  background:url(../elements/supplier/images/p-table-most-popu.png) no-repeat; position:absolute;} 
 
@media only screen and (max-width:480px){
.sitelogo{margin-bottom:6px;}
.login-sec {
    margin-top: 16px;
    text-align: center;
}
.banner-caption{display:none;}
.banner-caption h1{font-size:13px; line-height:16px; margin-bottom:2px;}
.banner-caption p{font-size:11px;}
.feature-contant-blog ul li{width:98%;}
.pricing-blog ul li{width:96%;}

.pricing-tabel-header{font-size:10px;}
.pricing-tabel-header ul li{width:18%;}
.pricing-tabel-header ul li:nth-child(1){padding-left:2px;}
.pricing-tabel-data-header h5{font-size:12px; padding:5px 0 5px 8px; width:90%;}
.pricing-tabel-data ul li{font-size:9px; width:19%;}
.pricing-tabel-data ul li:nth-child(1){padding-left:10px;}
.pricing-table-m-popular{display:none;}

}
 
/***********************signup-sec***********************/
.signup-sec{} 
.signup-sec h1{margin:35px 0 50px; text-align:center; color:#044467; font-size:36px;}
.cover-container{width:70%; margin:20px auto 100px;} 
.field-sec {
    float: left;
    width: 60%;
}
.img-sec {
    float: right;
    width: 36%;
} 
.name-field{width:48%; float:left;} 
.name-field2{width:48%; float:right;}  
.fild-mar{margin-top:15px;} 
.field-select{width:50%;}

.signup-sec .cap{margin:2px 0;}
.signup-sec p{font-size:14px; color:#1e769e;}

.signup-sec p a{color:#1e769e; text-decoration:none; outline:none;}
.signup-sec p a:hover{color:#1e769e; text-decoration:underline; outline:none;}
.signup-sec p .fa{margin-right:6px;}
.sign-up-btn{margin:50px 0; text-align:center;}
.login-text { margin-bottom: 0;}
.login-text p {
    color: #191919;
    font-size: 14px;
    line-height: 20px;
}
.login-text p span {
    font-weight: bold;
}
.signup-btn{padding:10px 80px; background:#1e769e;}



/****************************gallery********************************/
.gallery-sec{margin-top:20px;}
.gallery-sec h1{color:#030202; font-size:35px; margin:20px 0;}
.gallery-sec ul li{
		list-style:none;
		width:23.5%;
		border:1px solid #ccc;
		margin:0.5%;
		display:inline-block;
		overflow:hidden;
		
	}

.gallery-sec ul li .image-holder{width:100%; height:207px;}
.gallery-sec ul li .text-holder{padding:10px;}
.gallery-sec ul li .text-holder p{margin-bottom:10px; color:#020202; font-size:15px;}
.gallery-sec ul li .text-holder p span{ color:#1e769e; }
.gallery-sec .text-holder ul{margin-top:10px; text-align:right;}
.gallery-sec .text-holder ul li{list-style:none; display:inline-block; margin:0 1px;
 font-size:15px; color:#979393; width:auto; border:0;}

.pagination > li .fa{font-size:20px; color:#21607b;}

/*/////////////////////////////////*/

a.slimNav_sk78-reveal { display: none; }

/* Responsive viewport a container gets added */
.slim-container .slim-bar { float: left; width: 100%; position: relative; background: #01334e; padding: 0; min-height: 0px; z-index: 999999; }
.slim-container a.slimNav_sk78-reveal { width: 22px; height: 22px; padding: 13px 13px 11px 13px; position: absolute; top: -62px; right: 10px!important; left:auto!important; cursor: pointer; color: #fff; text-decoration: none; font-size: 16px;  line-height: 22px; display: block; font-family: Arial, Helvetica, sans-serif; font-weight: 700; }
.slim-container a.slimNav_sk78-reveal span { display: block; background: #fff; height: 3px; margin-top: 3px; }
.slim-container .slim-nav { float: left; width: 100%; background: #002438; margin-top: 0px; }
.slim-container .slim-nav ul { padding: 0; margin: 0; width: 100%; list-style-type: none; }
.slim-container .slim-nav ul li { position: relative; float: left; width: 95%; }
.slim-container .slim-nav ul li a { display: block; float: left; width: 92%; padding: 1em 5%; margin: 0; text-align: left; color: #fff; border-top: 1px solid #383838; border-top: 1px solid rgba(255, 255, 255, 0.5); text-decoration: none; text-transform: uppercase; }
.slim-container .slim-nav ul li li a { width: 80%; padding: 1em 10%; border-top: 1px solid #f1f1f1; border-top: 1px solid rgba(255, 255, 255, 0.25); opacity: 0.75; filter: alpha(opacity=75); text-shadow: none !important; visibility: visible; }
.slim-container .slim-nav ul li.slim-last a { border-bottom: none; margin-bottom: 0; }
.slim-container .slim-nav ul li li li a { width: 70%; padding: 1em 15%; }
.slim-container .slim-nav ul li li li li a { width: 60%; padding: 1em 20%; }
.slim-container .slim-nav ul li li li li li a { width: 50%; padding: 1em 25%; }
.slim-container .slim-nav ul li a:hover { background: #252525; background: rgba(255, 255, 255, 0.1); }
.slim-container .slim-nav ul li a.slim-expand { margin-top: 1px; width: 26px; height: 15px; padding: 10px !important; text-align: center; position: absolute; right: 0; top: 0; z-index: 2; font-weight: 700; background: rgba(255, 255, 255, 0.1); border: none !important; border-left: 1px solid rgba(255, 255, 255, 0.4) !important; border-bottom: 1px solid rgba(255, 255, 255, 0.2) !important; }
.slim-container .slim-nav ul li a.slim-expand:hover { background: rgba(0, 0, 0, 0.9); }
.slim-container .slim-push { float: left; width: 100%; padding: 0; margin: 0; clear: both; }
.slim-nav .wrapper { width: 100%; padding: 0; margin: 0; }

/* Solutions to viewport issues */
.slim-container .slim-bar, .slim-container .slim-bar * { -webkit-box-sizing: content-box; -moz-box-sizing: content-box; box-sizing: content-box; }
.slim-remove { display: none !important; }

/*
    Colorbox Core Style:
    The following CSS is consistent between example themes and should not be altered.
*/
#colorbox, #cboxOverlay, #cboxWrapper{position:absolute; top:0; left:0; z-index:9999; overflow:hidden; -webkit-transform: translate3d(0,0,0);}
#cboxWrapper {max-width:none;}
#cboxOverlay{position:fixed; width:100%; height:100%;}
#cboxMiddleLeft, #cboxBottomLeft{clear:left;}
#cboxContent{position:relative;}
#cboxLoadedContent{overflow:auto; -webkit-overflow-scrolling: touch;}
#cboxTitle{margin:0;}
#cboxLoadingOverlay, #cboxLoadingGraphic{position:absolute; top:0; left:0; width:100%; height:100%;}
#cboxPrevious, #cboxNext, #cboxClose, #cboxSlideshow{cursor:pointer;}
.cboxPhoto{float:left; margin:auto; border:0; display:block; max-width:none; -ms-interpolation-mode:bicubic;}
.cboxIframe{width:100%; height:100%; display:block; border:0; padding:0; margin:0;}
#colorbox, #cboxContent, #cboxLoadedContent{box-sizing:content-box; -moz-box-sizing:content-box; -webkit-box-sizing:content-box;}

/* 
    User Style:
    Change the following styles to modify the appearance of Colorbox.  They are
    ordered & tabbed in a way that represents the nesting of the generated HTML.
*/
#cboxOverlay{background:url(../elements/supplier/images/overlay.png) repeat 0 0; opacity: 0.9; filter: alpha(opacity = 90);}
#colorbox{outline:0;}
    #cboxTopLeft{width:21px; height:21px; background:url(../elements/supplier/images/controls.png) no-repeat -101px 0;}
    #cboxTopRight{width:21px; height:21px; background:url(../elements/supplier/images/controls.png) no-repeat -130px 0;}
    #cboxBottomLeft{width:21px; height:21px; background:url(../elements/supplier/images/controls.png) no-repeat -101px -29px;}
    #cboxBottomRight{width:21px; height:21px; background:url(../elements/supplier/images/controls.png) no-repeat -130px -29px;}
    #cboxMiddleLeft{width:21px; background:url(../elements/supplier/images/controls.png) left top repeat-y;}
    #cboxMiddleRight{width:21px; background:url(../elements/supplier/images/controls.png) right top repeat-y;}
    #cboxTopCenter{height:21px; background:url(../elements/supplier/images/border.png) 0 0 repeat-x;}
    #cboxBottomCenter{height:21px; background:url(../elements/supplier/images/border.png) 0 -29px repeat-x;}
    #cboxContent{background:#fff; overflow:hidden;}
        .cboxIframe{background:#fff;}
        #cboxError{padding:50px; border:1px solid #ccc;}
        #cboxLoadedContent{margin-bottom:28px;}
        #cboxTitle{position:absolute; bottom:4px; left:0; text-align:center; width:100%; color:#949494;}
		  #cboxTitle span{color:#1e769e;}
        #cboxCurrent{position:absolute; bottom:4px; left:58px; color:#949494; display:none!important;}
        #cboxLoadingOverlay{background:url(../elements/supplier/images/loading_background.png) no-repeat center center;}
        #cboxLoadingGraphic{background:url(../elements/supplier/images/loading.gif) no-repeat center center;}

        /* these elements are buttons, and may need to have additional styles reset to avoid unwanted base styles */
        #cboxPrevious, #cboxNext, #cboxSlideshow, #cboxClose {border:0; padding:0; margin:0; overflow:visible; width:auto; background:none; }
        
        /* avoid outlines on :active (mouseclick), but preserve outlines on :focus (tabbed navigating) */
        #cboxPrevious:active, #cboxNext:active, #cboxSlideshow:active, #cboxClose:active {outline:0;}

        #cboxSlideshow{position:absolute; bottom:4px; right:30px; color:#0092ef;}
        #cboxPrevious{position:absolute; top:50%; left:0; background:url(../elements/supplier/images/controls.png) no-repeat -75px 0; width:25px; height:25px; text-indent:-9999px;}
        #cboxPrevious:hover{background-position:-75px -25px;}
        #cboxNext{position:absolute; top:50%; right:0px; background:url(../elements/supplier/images/controls.png) no-repeat -50px 0; width:25px; height:25px; text-indent:-9999px;}
        #cboxNext:hover{background-position:-50px -25px;}
        #cboxClose{position:absolute; bottom:0; right:0; background:url(../elements/supplier/images/controls.png) no-repeat -25px 0; width:25px; height:25px; text-indent:-9999px;}
        #cboxClose:hover{background-position:-25px -25px;}

/*
  The following fixes a problem where IE7 and IE8 replace a PNG's alpha transparency with a black fill
  when an alpha filter (opacity change) is set on the element or ancestor element.  This style is not applied to or needed in IE9.
  See: http://jacklmoore.com/notes/ie-transparency-problems/
*/
.cboxIE #cboxTopLeft,
.cboxIE #cboxTopCenter,
.cboxIE #cboxTopRight,
.cboxIE #cboxBottomLeft,
.cboxIE #cboxBottomCenter,
.cboxIE #cboxBottomRight,
.cboxIE #cboxMiddleLeft,
.cboxIE #cboxMiddleRight {
    filter: progid:DX.imageTransform.Microsoft.gradient(startColorstr=#00FFFFFF,endColorstr=#00FFFFFF);
}

    </style>