<form id="login-form" class="form-horizontal" method="post">
    <fieldset>
        <legend><h3>Administrator Login</h3></legend>
        <?php $form->renderBootstrap('username');?>
        <?php $form->renderBootstrap('password');?>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <?php echo $form->render('submit');?>
            </div>
        </div>
    </fieldset>
</form>