<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Edit Customer</h3>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post">
            <fieldset>
                <legend><h3>About Customer</h3></legend>
                <div class="tab-wrapper">
                    <div class="col-xs-8">
                        <?php $form->renderBootstrap('first_name'); ?>
                        <?php $form->renderBootstrap('last_name'); ?>
                        <?php $form->renderBootstrap('country'); ?>
                        <?php $form->renderBootstrap('state'); ?>
                        <?php $form->renderBootstrap('city'); ?>
                        <?php $form->renderBootstrap('status'); ?>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend><h3>Contact Detail</h3></legend>
                <div class="tab-wrapper">
                    <div class="col-xs-8">
                        <?php $form->renderBootstrap('nick_name'); ?>
                        <?php $form->renderBootstrap('email'); ?>
                        <?php $form->renderBootstrap('phone'); ?>
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend><h3>Reset Password</h3></legend>
                <div class="tab-wrapper">
                    <div class="col-xs-8">
                        <?php $form->renderBootstrap('password'); ?>
                        <?php $form->renderBootstrap('re_password'); ?>
                    </div>
                </div>
            </fieldset>
            <div class="col-lg-12 no-pad">
                <?php echo $form->render('submit'); ?>
                <?php echo $this->tag->linkTo(array('/admin/customers', 'Back', 'class' => 'btn btn-default')); ?>
            </div>
        </form>
    </div>
</div>
