<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-remove"></span> Remove Customer
        </h3>
    </div>
    <div class="panel-body">
        <div class="page-header">
            <h2>Are you sure! you want to remove <small><i>"<?php echo $member->firstName . ' ' . $member->lastName; ?>"</i></small> ?</h2>
        </div>
        <div class="col-lg-4">
            <form method="post">
                <input type="hidden" name="key" value="<?php echo md5('confirm'); ?>" />
                <input type="hidden" name="vendor_id" value="<?php echo $member->memberId; ?>" />
                <input type="submit" name="submit" class="btn btn-danger" value="Remove" />
                <?php echo $this->tag->linkTo(array('/admin/customers', 'Cancel', 'class' => 'btn btn-primary')); ?>
            </form>
        </div>
    </div>
</div>