<div class="panel panel-danger">
    <div class="panel-heading">Customer Details</div>
    <div class="panel-body">
        <div class="col-sm-6">
            <div class="col-sm-3 no-pad">
                <?php
                echo $this->tag->image(array(
                    $member->getAvatarUri(),
                    "alt" => $member->firstName,
                    "title" => $member->firstName,
                    "class" => "img-thumbnail",
                ));
                ?>
            </div>
            <div class="col-sm-9 no-pad">
                <dl class="dl-horizontal">
                    <dt>Name :</dt><dd><?php echo $member->firstName . ' ' . $member->lastName; ?></dd>
                    <dt>Nickname :</dt><dd><?php echo $member->nickName; ?></dd>
                    <dt>Address 1 :</dt><dd><?php echo $member->addressOne; ?></dd>
                    <dt>Address 2 :</dt><dd><?php echo $member->addressTwo; ?></dd>
                    <dt>Email Address :</dt><dd><?php echo $member->emailAddress; ?></dd>
                    <dt>Phone Number :</dt><dd><?php echo $member->phone; ?></dd>
                    <dt>City :</dt><dd><?php echo $member->city; ?></dd>
                    <dt>State :</dt><dd><?php echo $member->state ? $member->state->name : ''; ?></dd>
                    <dt>Country :</dt><dd><?php echo $member->country ? $member->country->name : ''; ?></dd>
                    <dt>ZIP :</dt><dd><?php echo $member->zipCode; ?></dd>
                    <dt>Status :</dt><dd><?php echo $member->getStatus(TRUE); ?></dd>
                    <dt>Member From :</dt><dd><?php echo \Tourpage\Helpers\Utils::formatDate($member->createdOn, \Tourpage\Helpers\Utils::DATE_FORMAT_LONG); ?></dd>
                </dl>
            </div>
        </div>
        <div class="col-sm-6 panel panel-default"><div id="customer_booking_graph"></div></div>
        <div class="col-sm-12">
            <?php echo $this->tag->linkTo(array('/admin/customers/edit/' . $member->memberId, 'Edit', 'class' => 'btn btn-info')); ?>
            <?php echo $this->tag->linkTo(array('/admin/customers/remove/' . $member->memberId, 'Remove', 'class' => 'btn btn-danger')); ?>
            <?php echo $this->tag->linkTo(array('/admin/customers', 'Back', 'class' => 'btn btn-success')); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    var bookingSeries = [<?php echo implode(',', $monthsQueue); ?>];
    var bookingChart = new Highcharts.Chart({
        chart: {renderTo: 'customer_booking_graph'},
        credits: {enabled: 0},
        title: {text: 'Booking Graph for <?php echo \Tourpage\Helpers\Utils::__getCurrentYear(); ?>'},
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        yAxis: {
            title: {text: 'Booking Amount (USD)'}
        },
        tooltip: {
            valuePrefix: 'USD '
        },
        series: [
            {
                name: 'Total Booking',
                data: bookingSeries
            }
        ]
    });
</script>
