<section id="bodysectionpdp">
    <div id="subWrap">
        <h1 class="wrap tit" style="margin-top:20px;"> Reset Password</h1>
        <div id="content" class="wrap">
            <form class="login__signup-form" method="post" accept-charset="utf-8">
                <fieldset style="margin: 3em 0">
                    <span>Enter the email address associated with your account and we'll send you a link to reset your password</span><br><br>
                    <input placeholder="Email Address" value="" name="email" type="email"><br><br>
                    <button class="btnn" type="send_reset_link">Send Reset Link</button>
                    <a href="<?php echo $this->url->get('/store/site/' . $storeVendor->vendorId . '/login'); ?>" class="btnn" type="cancel" id="forgot_password_cancel">cancel</a>
                </fieldset>
            </form>
        </div>
    </div>
</section>