<?php /*?><?php
$address = '112 W 42nd st,New York,NY,10021';
$location = \Tourpage\Helpers\Utils::getGeolocation($address);
$infowindowContent = '<div style="width:220px;height:120px;">';
$infowindowContent .= '<a href="'.$this->url->getBaseUri().'"><img style="height: 50px;" src="'.$this->url->getStatic(FRONT_END_DIR . 'images/logo_home.jpg').'"/></a><br/><br/>';
$infowindowContent .= '<i class="fa fa-building"></i> 112 42nd street New York NY 1121<br/>';
$infowindowContent .= '<i class="fa fa-phone"></i> +12 1234 1212 / 215 454 4455<br/>';
$infowindowContent .= '<i class="fa fa-envelope"></i> info@tourpage.net';
$infowindowContent .= '</div>';
?>
<div id="map" style="width:100%;height:350px;margin-top: 20px;"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQc2RC2E2C7SgUoML9D-Q-VMUt7Q6fEhA"></script>
<script type="text/javascript">
	function initializeMap() {
		var mapCenter = {
			lat : <?php echo $location->lat;?>,
			lng : <?php echo $location->lng . "\n";?>
		};
		var mapOptions = {
			zoom: 15,
			scrollwheel: false,
			center: new google.maps.LatLng(mapCenter.lat, mapCenter.lng),
			overviewMapControl: true,
			overviewMapControlOptions: {
				opened: true,
			},
		};
		var map = new google.maps.Map(document.getElementById('map'),mapOptions);
		var infowindow = new google.maps.InfoWindow({
			maxWidth: 500
		});
		var marker = new google.maps.Marker({
			position: new google.maps.LatLng(mapCenter.lat, mapCenter.lng),
			map: map,
		});
		google.maps.event.addListener(marker, 'click', (function(marker) {
			return function() {
				infowindow.setContent('<?php echo $infowindowContent;?>');
				infowindow.open(map, marker);
			}
		})(marker));
	}
	google.maps.event.addDomListener(window, 'load', initializeMap);
</script><?php */?>
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
				<h3>Contacts</h3>
				<p>112 42nd Street, New York NY, 10021</p>
				<p>+12 1234 1212 / 215 454 4455</p>
				<p>info@tourpage.net</p>
			</div>
			<?php /*<ul class="footerList">
				<li class="title">Best Tours</li>
				<?php
				$element = new Multiple\Frontend\Plugins\Elements();
				$tours = $element->getTours();
				?>
				<?php if ($tours && $tours->count() > 0) { ?>
					<?php foreach ($tours as $tour) { ?>
						<li><a href="<?php echo $tour->getUri();?>">- <?php echo $tour->tourTitle; ?></a></li>
					<?php } ?>
				<?php } ?>
			</ul>*/ ?>
			<div class="col-sm-3">
				<h3>About</h3>
				<ul class="footer-link">
					<li><a href="#">About Viator Tour Guides</a></li>
					<li><a href="#">Tour Guide Register</a></li>
					<li><a href="#">Sitemap</a></li>
					<li><a href="#">Privacy</a></li>
					<li><a href="#">T&amp;C’s</a></li>
					<li><a href="#">FAQ</a></li>
				</ul>
			</div>
			<div class="col-sm-3">
				<h3>To be Tourpage Member</h3>
				<ul class="footer-link">
					<li><a href="#">About Viator Tour Guides</a></li>
					<li><a href="#">Tour Guide Register</a></li>
					<li><a href="#">Sitemap</a></li>
					<li><a href="#">Privacy</a></li>
					<li><a href="#">T&amp;C’s</a></li>
					<li><a href="#">FAQ</a></li>
				</ul>
			</div>
			<div class="col-sm-4">
				<h3>Newsletter</h3>
				<p>Join out newsletter to keep be informed about offers and news.</p>
                <form class="newsletter-form">
                    <input type="email" placeholder="you@example.com">
                    <input type="submit" value="JOIN US">
                </form>
			</div>
		</div>
		<br><br>
		<div class="text-center">
			<p><?php echo \Tourpage\Helpers\Utils::__getCurrentYear();?> &copy; Tourpage, Inc. All rights reserved. Tourpage is a registered trademark of Tourpage, Inc.</p>
		</div>
	</div>
</footer>
