<section class="container">
<div class="pdp">
	<div style="float:left;width:70%">
		<h3 style="font-size:20px;line-height:20px;color:#000"><?php echo $tour->tourTitle; ?></h3>
		<h5 style="font-size:14px;line-height:25px;color:#000"><?php echo $tour->tourSubTitle; ?></h5>
		<?php //if ($tour->tourImages->count() > 0) { ?>
		<?php /* <div style="border:1px solid black;position:relative">
		  <img u="image" src="<?php echo $tour->getDefaultImage()->getImageUri(); ?>" style="width:100%;position:relative"/><br/>
		  <?php foreach ($tour->tourImages as $tourImage) { ?>
		  <img u="thumb" src="<?php echo $tourImage->getImageUri('thumb'); ?>" style="padding:0px 10px;width:25px" />
		  <?php } ?>
		  </div> */ ?>
		<?php //} ?>
		<?php if ($tour->tourImages->count() > 0) { ?>
			<div id="store-ad" class="carousel slide" data-ride="carousel">
				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<?php
					$c = 1;
					foreach ($tour->tourImages as $tourImage) {
						?>
						<div class="item<?php echo $c == 1 ? ' active' : ''; ?>">
							<img src="<?php echo $tourImage->getImageUri(); ?>" style="width: 1405px; height: 400px;">
						</div>
						<?php
						$c++;
					}
					?>
				</div>
				<?php if ($tour->tourImages->count() > 1) { ?>
					<!-- Controls -->
					<a class="left carousel-control" href="#store-ad" role="button" data-slide="prev">
						<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="right carousel-control" href="#store-ad" role="button" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				<?php } ?>
			</div>
		<?php } ?>
		<?php if ($tour->tourKeyHighlights && $tour->tourKeyHighlights->count() > 0) { ?>
			<div class="desc-section">
				<ul class="list-unstyled">
					<?php foreach ($tour->tourKeyHighlights as $tourKeyHighlight) { ?>
						<li><img style="width: 20px;hright: 20px;" src="<?php echo $tourKeyHighlight->keyHighlight->getIconUri(); ?>"> <?php echo $tourKeyHighlight->keyHighlight->keyhighlightTitle; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if ($tour->tourAttributes->count() > 0) { ?>
			<div class="desc-section">
				<?php foreach ($tour->tourAttributes as $tourAttribute) { ?>
					<?php if ($tourAttribute->attributeContent != '') { ?>
						<h2><?php echo $tourAttribute->key->keyName; ?></h2>
						<div style="border-bottom:1px solid #e8e8e8;margin-bottom: 10px;margin-left: 10px;">
							<?php echo \Tourpage\Helpers\Utils::decodeString($tourAttribute->attributeContent); ?>
						</div>
					<?php } ?>
				<?php } ?>
			</div>
		<?php } ?>
		<div class="review-section pull-left">
			<div class="desc-section pull-left">
				<?php /*<h2><span class="glyphicon glyphicon-edit"></span> Write your review and give some rate for "<em><?php echo $tour->tourTitle; ?></em>"</h2>
				<div class="review-form col-lg-12">
					<?php if ($this->member->isLoggedIn()) { ?>
					<form id="form-rr">
						<input type="hidden" name="form_action" value="review">
						<label>Your Rating: <div id="customer_rating" style="display: inline-block;"></div></label>
						<input type="hidden" id="rating_set" name="rating_set">
						<ol class="reivewForm">
							<li style="float: left; width: 48%; margin-right: 30px;">
								<label for="rrname">Your Name: </label>
								<?php if (!$this->member->isLoggedIn()) { ?>
									<input type="text" autocomplete="off" class="form-control" name="rrname" id="rrname">
								<?php } else { ?>
									<input type="text" autocomplete="off" class="form-control" name="rrname-dis" id="rrname-dis" value="<?php echo $this->member->getFullName(); ?>" disabled>
									<input type="hidden" autocomplete="off" class="form-control" name="rrname" id="rrname" value="<?php echo $this->member->getFullName(); ?>">
								<?php } ?>
							</li>
							<li style="float: left; width: 48%;">
								<label for="rremail">Email Address: </label>
								<?php if (!$this->member->isLoggedIn()) { ?>
									<input type="text" autocomplete="off" class="form-control" name="rremail" id="rremail">
								<?php } else { ?>
									<input type="text" autocomplete="off" class="form-control" name="rremail-dis" id="rremail-dis" value="<?php echo $this->member->getEmail(); ?>" disabled>
									<input type="hidden" autocomplete="off" class="form-control" name="rremail" id="rremail" value="<?php echo $this->member->getEmail(); ?>">
								<?php } ?>
							</li>
							<li style="float: left; width: 100%; margin-top: 10px;">
								<label for="rrtext">Your Review: </label>
								<textarea autocomplete="off" class="form-control" name="rrtext" id="rrtext"></textarea>
							</li>
							<li style="float: left; width: 100%; margin-top: 10px;">
								<input id="submit_reivew" type="submit" name="submit_reivew" value="Post Review" class="btn btn-default" />
							</li>
						</ol>
					</form>
					<?php } else { ?>
					<div class="alert alert-info text-center text-info">Please login to write your review. <?php echo $this->tag->linkTo(array('/auth/login', 'Click here to login'));?></div>
					<?php } ?>
				</div>*/ ?>
				<div class="reviews col-lg-12">
					<h2>
						<span class="glyphicon glyphicon-th-list"></span> Customers Reviews & Rating (<?php echo $reviews->count();?>)
						<?php if ($reviews->count() > 0) { ?>
							<div class="pull-right">
								<button class="btn btn-primary" onClick="redirectTo('<?php echo $this->url->get('/tour/reviews/' . $tour->tourId); ?>');">More Reviews</button>
							</div>
						<?php } ?>
					</h2>
					<?php if ($reviews->count() > 0) { ?>
						<div class="review-container pull-left">
							<a name="reviewslist"></a>
							<?php foreach ($reviews as $review) { ?>
								<div class="review-wrapper pull-left">
									<div class="col-sm-1" style="padding:0;">
										<?php
										$reviewerAvator = $this->url->getStatic(FRONT_END_DIR . 'images/reviewer_avatar_default.png');
										if ($review->isMember()) {
											if ($review->memberTourReview && $review->memberTourReview->count() > 0) {
												$reviewerAvator = $review->memberTourReview->member->getAvatarUri(\Tourpage\Models\Members::AVATAR_ICON);
											}
										}
										echo $this->tag->image(array(
											$reviewerAvator,
											"width" => 45,
											"height" => 45
										));
										?>
									</div>
									<div class="col-sm-11">
										<span id="star_count_<?php echo $review->reviewId; ?>"></span>
										<small><?php echo \Tourpage\Helpers\Utils::formatDate($review->reviewOn, \Tourpage\Helpers\Utils::DATE_FORMAT_LONG); ?></small>
										<p><?php echo \Tourpage\Helpers\Utils::decodeString($review->reviewContent); ?></p>
										<p class="text-left">- <small><em><?php echo \Tourpage\Helpers\Utils::decodeString($review->reviewByName); ?></em></small></p>
										<script>jQuery(function () {
												jQuery('#star_count_<?php echo $review->reviewId; ?>').rateYo({rating: <?php echo $review->starCount; ?>, starWidth: "20px", readOnly: true});
											});</script>
									</div>
									<div class="clear"></div>
								</div>
							<?php } ?>
						</div>
						
					<?php } else { ?>
						<p>No one has given review for "<em><?php echo $tour->tourTitle; ?></em>"</p>
					<?php } ?>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<div style="float: left;width: 29%;margin-left: 7px;">
		<h2 style="margin-top: 21px;padding-left: 0;">Book This Tour Now</h2>
		<div class="booking-section">
			<div class="rightbox">
				<div class="info">
					<h2>Operator of this tour:</h2>
					<?php //if ($tour->tourVendor->vendor->getAvatarUri()) { ?>
					<figure class="line-color">
						<?php
						$vendorAvator = $this->url->getStatic(FRONT_END_DIR . 'images/no_face.png');
						if ($tour->tourVendor->vendor->getAvatarUri()) {
							$vendorAvator = $tour->tourVendor->vendor->getAvatarUri();
						}
						echo $this->tag->image(array(
							$vendorAvator,
							"alt" => $tour->tourVendor->vendor->firstName,
							"title" => $tour->tourVendor->vendor->firstName,
							"width" => 80,
							"height" => 80
						));
						?>
					</figure>
					<?php //}     ?>
					<ul class="info">
						<li class="name"><?php echo $this->tag->linkTo(array($tour->tourVendor->vendor->getStorFrontUri(), $tour->tourVendor->vendor->businessName, 'local' => false)); ?></li>
						<?php if ($tour->tourVendor->vendor->estd) { ?>
							<li class="since">Established since <?php echo $tour->tourVendor->vendor->estd; ?></li>
						<?php } ?>
						<li class="name">Operator: <?php echo $tour->tourVendor->vendor->firstName . ' ' . $tour->tourVendor->vendor->lastName; ?></li>
						<li class="location">Location: <?php echo $tour->tourVendor->vendor->state->name . ', ' . $tour->tourVendor->vendor->country->name; ?></li>
						<li class="name">Email: <?php echo $tour->tourVendor->vendor->emailAddress; ?></li>
						<?php if ($tour->tourVendor->vendor->phone) { ?>
							<li class="name">Phone: <?php echo $tour->tourVendor->vendor->phone; ?></li>
						<?php } ?>
					</ul>
					<p class="clearboth"></p>
				</div>
			</div>
			<p class="clearboth"></p>
			<form id="tour_booking_form" method="post">
				<input type="hidden" name="form_action" value="booking">
				<ul>
					<li>From <div class="tour-price"><?php echo \Tourpage\Helpers\Utils::formatCurrency($tour->tourPrice->getPrice()); ?></div> <?php //echo $tour->tourPrice->data->priceTypeText; ?></li>
					<?php if (isset($tour->tourDuration->totalDays)) { ?>
						<li><em>(for <?php echo $tour->tourDuration->totalDays; ?>days <?php echo ($tour->tourDuration->totalDays - 1); ?>nights)</em></li>
					<?php } ?>
					<?php if ($tour->tourPrice->hasDiscount(true, true)) { ?>
						<li>
							<div class="alert alert-info"><strong><?php echo $tour->tourPrice->data->discount->price; ?>% Discount</strong> From 
								<?php echo \Tourpage\Helpers\Utils::formatDate(strtotime($tour->tourPrice->data->discount->start), \Tourpage\Helpers\Utils::DATE_FORMAT_SHORT); ?> To 
								<?php echo \Tourpage\Helpers\Utils::formatDate(strtotime($tour->tourPrice->data->discount->end), \Tourpage\Helpers\Utils::DATE_FORMAT_SHORT); ?></div>
						</li>
					<?php } ?>
					<?php if ($tour->tourPrice->hasMultiPurchesDiscount()) { ?>
						<?php
						$headCountUnit = ' Person(s)';
						if ($tour->tourPrice->data->priceType == \Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) {
							$headCountUnit = ' Group(s)';
						}
						?>
						<li>
							<div class="alert alert-info">
								<strong><?php echo $tour->tourPrice->data->discount->multiplePurchase->percentage; ?>% Discount</strong> if booked for 
								<?php echo $tour->tourPrice->data->discount->multiplePurchase->count; ?> <?php echo $headCountUnit; ?>
							</div>
						</li>
					<?php } ?>

					<?php
					switch ($tour->tourDuration->lengthType) {
						case \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE:
							?>
							<li>Choose your journey date <div id="bookingdatepicker"></div></li>
							<li id="jdpanel" style="display: none;">
								<hr />
								<div>Departure: <date id="st">________</date></div>
								<div>Arrival: <date id="ed">________</date></div>
								<input type="hidden" id="jstd" name="jstd">
								<input type="hidden" id="jedd" name="jedd">
							</li>
							<?php
							break;
						case \Tourpage\Models\Tours::LENGTH_FIXED_DAYS_CODE:
							?>
							<li>
								<div>Departure: <?php echo \Tourpage\Helpers\Utils::formatDate($tour->tourStartFrom, \Tourpage\Helpers\Utils::DATE_FORMAT_LONG); ?></div>
								<div>Arrival: <?php echo \Tourpage\Helpers\Utils::formatDate($tour->tourEndTo, \Tourpage\Helpers\Utils::DATE_FORMAT_LONG); ?></div>
								<input type="hidden" id="jstd" name="jstd" value="<?php echo \Tourpage\Helpers\Utils::formatMySqlToDatepicker($tour->tourStartFrom); ?>">
								<input type="hidden" id="jedd" name="jedd" value="<?php echo \Tourpage\Helpers\Utils::formatMySqlToDatepicker($tour->tourEndTo); ?>">
							</li>
							<?php
							break;
						case \Tourpage\Models\Tours::LENGTH_SINGLE_DAY_CODE:
							?>
							<li>Choose your journey date <div id="bookingdatepicker"></div></li>
							<li id="jdpanel" style="display: none;">
								<hr />
								<div>Choosen Date: <date id="st">________</date></div>
								<input type="hidden" id="jstd" name="jstd">
							</li>
							<?php
							break;
						case \Tourpage\Models\Tours::LENGTH_HOURLY:
							?>
							<li>Choose your journey date <div id="bookingdatepicker"></div></li>
							<li id="jdpanel" style="display: none;">
								<hr />
								<div>Choosen Date: <date id="st">________</date></div>
								<input type="hidden" id="jstd" name="jstd">
							</li>
							<?php /* <input type="hidden" id="jstd" name="jstd"> */ ?>
							<?php /* <li>Choose your preferable time slot
							  <?php if (count($tour->tourDuration->times) > 0) { $sl = 1; ?>
							  <?php foreach ($tour->tourDuration->times as $timeSlot) { ?>
							  <label style="width: 100%">
							  <input type="radio" name="tour_time_slot" value="<?php echo base64_encode(serialize($timeSlot));?>"<?php echo $sl == 1 ? ' checked="checked"' : '';?>>
							  <?php echo \Tourpage\Helpers\Utils::padInt($timeSlot->start->hours).':'.\Tourpage\Helpers\Utils::padInt($timeSlot->start->minutes).' '.($timeSlot->start->hours >= 12 ? 'PM' : 'AM');?>
							  To <?php echo \Tourpage\Helpers\Utils::padInt($timeSlot->end->hours).':'.\Tourpage\Helpers\Utils::padInt($timeSlot->end->minutes).' '.($timeSlot->end->hours >= 12 ? 'PM' : 'AM');?>
							  </label>
							  <?php $sl++; } ?>
							  <?php } ?>
							  </li> */ ?>
							<?php break; ?>
					<?php } ?>
				</ul>
				<?php if ($tour->tourOptions->count() > 0) { ?>
					<hr />
					<h3>Other Options</h3>
					<ul>
						<?php foreach ($tour->tourOptions as $tourOption) { ?>
							<li><input name="tour_opt[<?php echo $tourOption->optionId; ?>]" type="checkbox" value="<?php echo $tourOption->optionPrice; ?>" onclick="addPrice<?php echo $tourOption->optionPriceType; ?>(this);" prtype="<?php echo $tourOption->optionPriceType; ?>"> <?php echo $tourOption->optionName . ' ' . \Tourpage\Helpers\Utils::formatCurrency($tourOption->optionPrice) . ' ' . $tourOption->optionPriceTypeText; ?></li>
						<?php } ?>
					</ul>
				<?php } ?>
				<ul>
					<hr />
					<?php if ($tour->tourPrice->data->priceType == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_PERSON_CODE) { ?>
						<?php
						foreach ($ageGroups as $groupKey => $groupTitle) {
							if (isset($tour->tourPrice->data->priceGroup[$groupKey])) {
								?>
								<li><?php echo $groupTitle . ' ( ' . $tour->tourPrice->data->priceGroup[$groupKey]['age_type'] . ' ' . $tour->tourPrice->data->priceGroup[$groupKey]['age'] . ' )'; ?>
									<input type="text" value="<?php echo $groupKey == 'a' ? 1 : 0; ?>" name="head_count[<?php echo $groupKey; ?>]" class="spiner hc <?php echo $groupKey; ?>">
									<input type="hidden" id="sp_hid<?php echo $groupKey; ?>" value="<?php echo $groupKey == 'a' ? $tour->tourPrice->data->priceGroup[$groupKey]['price'] : 0; ?>">
								</li>
								<?php
							}
						}
						?>
					<?php } ?>
					<?php if ($tour->tourPrice->data->priceType == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) { ?>
						<li>
							Number of Group(s) <input type="text" value="1" min="1" name="group_head_count" size="10" class="spiner ghc">
							<input type="hidden" id="sp_hidghc" value="<?php echo $tour->tourPrice->getPrice(TRUE); ?>">
						</li>
					<?php } ?>
				</ul>
				<hr />
				<div class="total">
					<input type="hidden" name="total_amount" id="total_amount" value="<?php echo $tour->tourPrice->getPrice(TRUE); ?>" org="<?php echo $tour->tourPrice->getPrice(); ?>">
					Total: <span id="amount"><?php echo \Tourpage\Helpers\Utils::formatCurrency($tour->tourPrice->getPrice(TRUE)); ?></span>
				</div>
				<div class="availibility hidden">
					<p class="text-info text-right">Checking for availibility...</p>
					<div class="progress">
						<div class="progress-bar progress-bar-success progress-bar-striped active" style="width: 100%"></div>
					</div>
				</div>
				<div id="availibility_content"></div>
				<hr />
				<?php if ($tour->isBookingActive()) { ?>
					<?php /* <button class="btnn" id="tour_booking_submit">Book now</button> */ ?>
					<button data-loading-text="Wait..." id="tour_booking_submit" class="btn btn-social btn-facebook btn-pad"><i class="fa fa-book"></i> Book now</button>
				<?php } else { ?>
					<div class="alert alert-info text-center">Booking currently not available</div>
				<?php } ?>
				<?php if (!$this->member->isFavoriteTour($tour->tourId)) { ?>
					<a id="tour_add_to_fav" class="btn btn-social btn-adn btn-pad" onclick="return addToFavTour('<?php echo $tour->tourId; ?>', '<?php echo $tour->tourVendor->vendor->vendorId; ?>');"><i class="fa fa-heart"></i> Add to favorite</a>
				<?php } ?>

			</form>
			<?php if (!empty($tour->tourPolicy) || !empty($tour->tourVendor->vendor->policy)) { ?>
				<h2><a class="link_tc" id="tour_tc">Please See Our Terms & Conditions Here</a></h2>
				<!-- Modal -->
				<div class="modal fade" id="model-tour-tc" tabindex="-1" role="dialog" aria-labelledby="model_tc">
					<div class="modal-dialog modal-lg" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
								<h4 class="modal-title" id="model_tc">Terms & Conditions</h4>
							</div>
							<div class="modal-body">
								<?php echo !empty($tour->tourPolicy) ? \Tourpage\Helpers\Utils::decodeString($tour->tourPolicy) : (!empty($tour->tourVendor->vendor->policy) ? \Tourpage\Helpers\Utils::decodeString($tour->tourVendor->vendor->policy) : ''); ?>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>
		</div>
		<div class="booking-section">
			<div class="more-item">
				<?php if ($otherTours->fromVendor->count() > 0) { ?>
					<h3>More from <?php echo $this->tag->linkTo(array($tour->tourVendor->vendor->getStorFrontUri(), $tour->tourVendor->vendor->businessName, 'local' => false)); ?></h3>
					<div id="from-vendor-tour" class="carousel slide from-vendor" data-ride="carousel">
						<div class="carousel-inner" role="listbox">
							<?php
							$fvcatv = 1;
							foreach ($otherTours->fromVendor as $fromVendor) {
								?>
								<div class="item<?php echo ($fvcatv == 1 ? ' active' : ''); ?>">
									<div class="from-vendor-item thumbnail">
										<figure class="text-center">
											<a href="<?php echo $fromVendor->tour->getUri(); ?>" class="thumbnail">
												<img src="<?php echo $fromVendor->tour->getDefaultImage() ? $fromVendor->tour->getDefaultImage()->getImageUri('thumb') : ''; ?>" style="width:300px;height:200px"/>
											</a>
										</figure>
										<ol>
											<li class="tit"><a href="<?php echo $fromVendor->tour->getUri(); ?>"><?php echo $fromVendor->tour->tourTitle; ?></a></li>
											<li>by <a href="<?php echo $fromVendor->vendor->getStorFrontUri(); ?>"><?php echo $fromVendor->vendor->firstName . ' ' . $fromVendor->vendor->lastName; ?></a></li>
										</ol>
									</div>
								</div>
								<?php $fvcatv++; ?>
							<?php } ?>
						</div>
						<?php if ($otherTours->fromVendor->count() > 1) { ?>
							<!-- Controls -->
							<a class="left carousel-control" href="#from-vendor-tour" role="button" data-slide="prev">
								<span class="glyphicon glyphicon-chevron-left left-box-control" aria-hidden="true"></span>
								<span class="sr-only">Previous</span>
							</a>
							<a class="right carousel-control" href="#from-vendor-tour" role="button" data-slide="next">
								<span class="glyphicon glyphicon-chevron-right left-box-control" aria-hidden="true"></span>
								<span class="sr-only">Next</span>
							</a>
						<?php } ?>
					</div>
				<?php } ?>
				<?php if ($otherTours->fromCategory->count() > 0) { ?>
					<h3>You may also like</h3>
					<div id="from-category-tour" class="carousel slide from-category" data-ride="carousel">
						<div class="carousel-inner" role="listbox">
							<?php
							$fccatv = 1;
							foreach ($otherTours->fromCategory as $fromCategory) {
								?>
								<div class="item<?php echo ($fccatv == 1 ? ' active' : ''); ?>">
									<div class="from-category-item thumbnail">
										<figure class="text-center">
											<a href="<?php echo $fromCategory->tour->getUri(); ?>" class="thumbnail">
												<img src="<?php echo $fromCategory->tour->getDefaultImage() ? $fromCategory->tour->getDefaultImage()->getImageUri('thumb') : ''; ?>" style="width:300px;height:200px"/>
											</a>
										</figure>
										<ol>
											<li class="tit"><a href="<?php echo $fromCategory->tour->getUri(); ?>"><?php echo $fromCategory->tour->tourTitle; ?></a></li>
											<li>by <a href="<?php echo $fromCategory->tour->tourVendor->vendor->getStorFrontUri(); ?>"><?php echo $fromCategory->tour->tourVendor->vendor->firstName . ' ' . $fromCategory->tour->tourVendor->vendor->lastName; ?></a></li>
										</ol>
									</div>
								</div>
								<?php $fccatv++; ?>
							<?php } ?>
						</div>
						<?php if ($otherTours->fromCategory->count() > 1) { ?>
							<!-- Controls -->
							<a class="left carousel-control" href="#from-category-tour" role="button" data-slide="prev">
								<span class="glyphicon glyphicon-chevron-left left-box-control" aria-hidden="true"></span>
								<span class="sr-only">Previous</span>
							</a>
							<a class="right carousel-control" href="#from-category-tour" role="button" data-slide="next">
								<span class="glyphicon glyphicon-chevron-right left-box-control" aria-hidden="true"></span>
								<span class="sr-only">Next</span>
							</a>
						<?php } ?>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
</section>
<style>
    .pdp {font-size:14px;line-height:24px;}
    .pdp h2{padding:10px;font-size:15px;font-weight:bold}
    .pdp ul{list-style:none}
    .pdp h3{margin-top:20px;}
    .pdp h4{margin-top:20px;}
    h4.modal-title{margin:0}
    .tour-price{display: inline;font-size: 24px;font-weight: bold;}
    .booking-section, .desc-section{/*border: 1px solid #9e9e9e;*/padding: 10px;margin-top: 7px;width: 100%;}
    .hasDatepicker{margin-bottom: 10px;}
    a.ui-datepicker-selected-bg, .ui-state-active{border-color: #ff0000 !important;color: #ff0000 !important;}
    .ui-datepicker td span, .ui-datepicker td a{text-align: center;}
    span.ui-state-default{cursor: not-allowed;}
    span.ui-spinner{height: 25px;margin-bottom: 10px;width: 70px;}
    input[type="text"].spiner{height: 30px;margin: 0;padding: 0 0 0 30px;width: 100%;}
    a.ui-spinner-down{left: 0;}
    .ui-spinner a.ui-spinner-button{border: none;top: 6px;cursor: pointer;}
    .btn-pad{padding: 6px 12px 6px 40px;}
    div.total{font-size: 24px;font-weight: bold;margin-bottom: 10px;}
    div.availibility p{margin-bottom: 0px;}
    .ui-widget-content{width: 100%;}
    .link_tc{cursor:pointer;}/*.modal-dialog{margin-top:100px;}*/
    form#tour_booking_form{padding:10px}
    .rightbox{width: 100%;}
    .rightbox .info{background: none; padding-top: 0;}
    .from-vendor, .from-category{width: 100%;margin-top: 7px;/*padding: 10px;*/}
    .from-vendor .from-vendor-item, .from-category .from-category-item{/*border: 1px solid #e8e8e8;padding: 5px;margin-right:15px;*/}
    .from-vendor .from-vendor-item ol li, .from-category .from-category-item ol li{list-style: none;}
    .more-item{padding-left:0; padding-right:0;}
    .reivewForm{list-style:none;float:left;width:100%}
    .reivewForm li label{display:inline-block;width:100px}
    .reivewForm li{text-align:left}
    .review-form{padding:10px;width: 100%;}
    .review-section{width: 100%;}
    .left-box-control {margin-top:-70px !important}
    .jumbotron {padding-left: 48px;padding-right: 48px;}
</style>
<script type="text/javascript">
    var disableDates = [<?php echo count($disablDates) > 0 ? implode(',', $disablDates) : ''; ?>];
    var accissableWeekDays = [<?php echo count($tour->tourDuration->weekDays) > 0 ? implode(',', $tour->tourDuration->weekDays) : ''; ?>];
    var currentDate = new Date();
    var startDate = new Date('<?php echo $tour->tourStartFrom ? \Tourpage\Helpers\Utils::formatMySqlToDatepicker($tour->tourStartFrom) : ''; ?>');
    var endDate = new Date('<?php echo $tour->tourEndTo ? \Tourpage\Helpers\Utils::formatMySqlToDatepicker($tour->tourEndTo) : ''; ?>');
    var checkAvailState = false;
    var cacheData = {};
    if (currentDate >= startDate) {
        startDate = currentDate;
    }
<?php if ($tour->tourDuration->lengthType == \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE) { ?>
        var totalDays = <?php echo $tour->tourDuration->totalDays; ?>;
<?php } ?>
<?php if ($tour->tourPrice->hasDiscount()) { ?>
        var discountPrecentage = <?php echo $tour->tourPrice->data->discount->price; ?>;
<?php } ?>
<?php if ($tour->tourPrice->hasMultiPurchesDiscount()) { ?>
        var discountMultiplePurches = {
            precentage: <?php echo $tour->tourPrice->data->discount->multiplePurchase->percentage; ?>,
            count: <?php echo $tour->tourPrice->data->discount->multiplePurchase->count; ?>
        };
<?php } ?>
<?php
$groupKeys = array_keys($tour->tourPrice->data->priceGroup);
$gks = '';
if (count($groupKeys) > 0) {
    foreach ($groupKeys as $gk) {
        $gks .= '"' . $gk . '",';
    }
}
$gks = (substr($gks, -1) == ',' ? substr($gks, 0, -1) : $gks);
echo 'var groupKeys = [' . $gks . '];';
?>
    jQuery(function () {
        var $rateYo = jQuery('#customer_rating').rateYo({
            //rating: 1,
            fullStar: true,
            starWidth: "20px",
            onSet: function (rating, rateYoInstance) {
                jQuery('#rating_set').val(rating);
            }
        });

        jQuery('form#form-rr').submit(function (evt) {
            evt.preventDefault();
            var errors = [],
                    ratingSet = jQuery('#rating_set'),
                    customerName = jQuery('#rrname'),
                    customerEmail = jQuery('#rremail'),
                    customerReview = jQuery('#rrtext');
            jQuery('.error-field').removeClass('error-field');
            jQuery('span.error-message').remove();
            if (customerName.val().length <= 0) {
                errors.push(customerName.attr('id') + ':Please Write Your Name');
            }
            if (customerEmail.val().length <= 0) {
                errors.push(customerEmail.attr('id') + ':Please Write Your Email');

            } else {
                if (!isValidEmail(customerEmail.val())) {
                    errors.push(customerEmail.attr('id') + ':Email Address is not valid');
                }
            }
            if (customerReview.val().length <= 0) {
                errors.push(customerReview.attr('id') + ':Please Write Your Review');
            }
            if (errors.length > 0) {
                for (var e in errors) {
                    var errorData = errors[e].split(':');
                    if (typeof errorData[0] != 'undefined' && errorData[0].length > 0) {
                        var element = jQuery('#' + errorData[0]);
                        element.addClass('error-field');
                        var message = jQuery('<span/>');
                        message.html(errorData[1]);
                        message.addClass('error-message');
                        element.after(message);
                    }
                }
            } else {
                var reviewPost = jQuery.post('<?php echo $this->url->get('/ajax/customerReview'); ?>', {
                    'customer_name': customerName.val(),
                    'customer_email': customerEmail.val(),
                    'customer_review': customerReview.val(),
                    'rating_set': ratingSet.val(),
                    'member_id': <?php echo $this->member->isLoggedIn() ? $this->member->getId() : 0; ?>,
                    'review_on': {
                        'type': 'tour',
                        'id': '<?php echo $tour->tourId; ?>',
                        'vid': '<?php echo $tour->tourVendor->vendorId; ?>'
                    }
                });
                reviewPost.done(function (data) {
                    var response = jQuery.parseJSON(data);
                    if (response.success) {
<?php if (!$this->member->isLoggedIn()) { ?>
                            customerName.val('');
                            customerEmail.val('');
<?php } ?>
                        customerReview.val('');
                        $rateYo.rateYo("rating", 1);
                        alert(response.message);
                        window.location.reload();
                    } else {
                        alert('Error on sending message');
                    }
                });
            }
        });

        jQuery('button#tour_booking_submit').on('click', function (event) {
            event.preventDefault();
            var error = [], headCount = 0, selectedDate = {}, tourPriceType = '<?php echo $tour->tourPrice->data->priceType; ?>';
            var availibilityProgress = jQuery('.availibility');
            var availibilityContent = jQuery('#availibility_content');
<?php
switch ($tour->tourDuration->lengthType) {
    case \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE:
        ?>
                    var std = jQuery('#jstd').val();
                    var edd = jQuery('#jedd').val();
                    if (std === '' || edd === '') {
                        error.push('Please select your journey date');
                    } else {
                        selectedDate.std = std;
                        selectedDate.edd = edd;
                    }
        <?php
        break;
    case \Tourpage\Models\Tours::LENGTH_FIXED_DAYS_CODE:
        ?>
                    var std = jQuery('#jstd').val();
                    var edd = jQuery('#jedd').val();
                    selectedDate.std = std;
                    selectedDate.edd = edd;
        <?php
        break;
    case \Tourpage\Models\Tours::LENGTH_SINGLE_DAY_CODE:
    case \Tourpage\Models\Tours::LENGTH_HOURLY:
        ?>
                    var std = jQuery('#jstd').val();
                    if (std === '') {
                        error.push('Please select your journey date');
                    } else {
                        selectedDate.std = std;
                    }
        <?php break; ?>
<?php } ?>
            if (error.length === 0) {
                switch (tourPriceType) {
                    case '<?php echo Tourpage\Models\ToursPrice::PRICE_TYPE_PER_PERSON_CODE; ?>':
                        for (var k in groupKeys) {
                            var hc = jQuery('input[name="head_count[' + groupKeys[k] + ']"]').val();
                            headCount = parseInt(headCount) + parseInt(hc);
                        }
                        break;
                    case '<?php echo Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE; ?>':
                        headCount = jQuery('input[name="group_head_count"]').val();
                        break;
                }
                if (checkAvailState) {
                    var cstd = new Date(cacheData.std);
                    var sstd = new Date(selectedDate.std);
                    if ((cstd.getTime() !== sstd.getTime()) || (cacheData.headCount != headCount)) {
                        checkAvailState = false;
                        availibilityContent.html('');
                    }
                }
                if (!checkAvailState) {
                    var $btn = jQuery(this).button('loading');
                    availibilityProgress.removeClass('hidden');
                    var availibilityPost = jQuery.post('<?php echo $this->url->get('/ajax/checkTourAvailibility/' . $tour->tourId); ?>', {
                        'tour_length_type': '<?php echo $tour->tourDuration->lengthType; ?>',
                        'tour_price_type': tourPriceType,
                        'head_count': headCount,
                        'selected_date': selectedDate,
                    });
                    availibilityPost.done(function (data) {
                        var response = jQuery.parseJSON(data);
                        if (response.availableForBooking) {
                            if (typeof response.timeOptions !== 'undefined') {
                                checkAvailState = true;
                                cacheData.std = selectedDate.std;
                                cacheData.headCount = headCount;
                                setTimeout(function () {
                                    $btn.button('reset').blur();
                                    availibilityProgress.addClass('hidden');
                                    var contentHtml = '<hr/>';
                                    contentHtml += '<h2 style="padding-left:0;">Choose your preferable time slot</h2>';
                                    contentHtml += response.timeOptions;
                                    availibilityContent.html(contentHtml);
                                }, 2000);
                            } else {
                                setTimeout(function () {
                                    availibilityProgress.addClass('hidden');
                                    jQuery('form#tour_booking_form').submit();
                                }, 2000);
                            }
                        } else {
                            if (response.message.length > 0) {
                                setTimeout(function () {
                                    $btn.button('reset').blur();
                                    availibilityProgress.addClass('hidden');
                                    availibilityContent.html("<div class=\"alert alert-info\">" + response.message + "</div>");
                                }, 2000);
                            }
                        }
                    });
                } else {
                    jQuery('form#tour_booking_form').submit();
                }
            } else {
                var errorString = 'ERROR:\n';
                for (var e in error) {
                    errorString += (parseInt(e) + 1) + '. ' + error[e];
                }
                alert(errorString);
            }
        });
        jQuery('#bookingdatepicker').datepicker({
            //changeMonth: true,
            //changeYear: true,
            //showOtherMonths: true,
            minDate: startDate,
            maxDate: endDate,
            beforeShowDay: function (d) {
                var accissableDay = true;
                var datePickerDateString = jQuery.datepicker.formatDate('mm/dd/yy', d);
                if (jQuery.inArray(d.getDay(), accissableWeekDays) === -1) {
                    accissableDay = false;
                } else {
					if (jQuery.inArray(datePickerDateString, disableDates) === 0) {
						accissableDay = false;
					}
				}
                <?php
                switch ($tour->tourDuration->lengthType) {
                    case \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE:
                    case \Tourpage\Models\Tours::LENGTH_FIXED_DAYS_CODE:
                    case \Tourpage\Models\Tours::LENGTH_SINGLE_DAY_CODE:
                        ?>
                        if (d.getDate() === currentDate.getDate() && d.getMonth() === currentDate.getMonth()) {
                            accissableDay = false;
                        }
                        <?php break; ?>
                <?php } ?>
                return [accissableDay];
            },
            onSelect: function (dateText, dp) {
                setTimeout(function () {
                    <?php
                    switch ($tour->tourDuration->lengthType) {
                        case \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE:
                            ?>
                            var std = jQuery('#bookingdatepicker').datepicker("getDate");
                            var totalDates = betweenDates(std, endDate);
                            if (totalDates.length >= totalDays) {
                                var edd = new Date(std.getFullYear(), std.getMonth(), std.getDate() + (totalDays - 1));
                                if (!jQuery('#jdpanel').is(':visible')) {
                                    jQuery('#jdpanel').show();
                                }
                                jQuery('#st').html(std.toLocaleDateString("en-US"));
                                jQuery('#ed').html(edd.toLocaleDateString("en-US"));
                                jQuery('#jstd').val(std.toLocaleDateString("en-US"));
                                jQuery('#jedd').val(edd.toLocaleDateString("en-US"));
                            } else {
                                alert('Booking not available on ' + dateText);
                            }
                            <?php
                            break;
                        case \Tourpage\Models\Tours::LENGTH_SINGLE_DAY_CODE:
                        case \Tourpage\Models\Tours::LENGTH_HOURLY:
                            ?>
                            var std = jQuery('#bookingdatepicker').datepicker("getDate");
                            if (!jQuery('#jdpanel').is(':visible')) {
                                jQuery('#jdpanel').show();
                            }
                            jQuery('#st').html(std.toLocaleDateString("en-US"));
                            jQuery('#jstd').val(std.toLocaleDateString("en-US"));
                            <?php break; ?>
                    <?php } ?>
                }, 5);
            }
        });
<?php if ($tour->tourPrice->data->priceType == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_PERSON_CODE) { ?>
    <?php foreach ($ageGroups as $groupKey => $groupTitle) { ?>
        <?php if (isset($tour->tourPrice->data->priceGroup[$groupKey])) { ?>
                    jQuery('.<?php echo $groupKey; ?>').on('keypress', function () {
                        return false;
                    });
                    jQuery('.<?php echo $groupKey; ?>').spinner({
                        min: <?php echo $groupKey == 'a' ? 1 : 0; ?>,
                        icons: {down: "ui-icon-minusthick", up: "ui-icon-plusthick"},
                    });
                    jQuery('.<?php echo $groupKey; ?>').on('spin', function (event, ui) {
                        var amount = <?php echo $tour->tourPrice->data->priceGroup[$groupKey]['price']; ?>;
                        jQuery('#sp_hid<?php echo $groupKey; ?>').val(ui.value * amount);
                    });
                    jQuery('.<?php echo $groupKey; ?>').on('spinstop', function (event, ui) {
                        var totalAmount = 0;
                        for (var k in groupKeys) {
                            totalAmount = parseInt(totalAmount) + parseInt(jQuery('#sp_hid' + groupKeys[k]).val());
                        }
            <?php if ($tour->tourOptions->count() > 0) { ?>
                            jQuery('input[name^="tour_opt"]').each(function (i, el) {
                                if (jQuery(el).is(':checked')) {
                                    var prType = jQuery(el).attr('prtype');
                                    var prAmount = jQuery(el).val();
                                    switch (prType) {
                                        case '<?php echo \Tourpage\Models\ToursOptions::OPTION_PER_PERSON_CODE; ?>':
                                            var headCount = 0, headCountTotal = 0;
                                            for (var k in groupKeys) {
                                                var hc = jQuery('input[name="head_count[' + groupKeys[k] + ']"]').val();
                                                headCount = parseInt(headCount) + parseInt(hc);
                                            }
                                            headCountTotal = headCount * prAmount;
                                            totalAmount = parseInt(totalAmount) + parseInt(headCountTotal);
                                            break;
                                        case '<?php echo \Tourpage\Models\ToursOptions::OPTION_PER_GROUP_CODE; ?>':
                                            var headCountTotal = jQuery(el).val();
                                            totalAmount = parseInt(totalAmount) + parseInt(headCountTotal);
                                            break;
                                    }
                                }
                            });
            <?php } ?>
                        jQuery('#total_amount').attr('org', totalAmount);
                        if (typeof discountPrecentage !== 'undefined') {
                            totalAmount = totalAmount - ((totalAmount * discountPrecentage) / 100);
                        }
                        if (typeof discountMultiplePurches !== 'undefined') {
                            var headCount = 0;
                            for (var k in groupKeys) {
                                var hc = jQuery('input[name="head_count[' + groupKeys[k] + ']"]').val();
                                headCount = parseInt(headCount) + parseInt(hc);
                            }
                            if (headCount >= discountMultiplePurches.count) {
                                totalAmount = totalAmount - ((totalAmount * discountMultiplePurches.precentage) / 100);
                            }
                        }
                        jQuery('span#amount').html(formatMoney(totalAmount))
                        jQuery('#total_amount').val(totalAmount);
                    });
        <?php } ?>
    <?php } ?>
<?php } ?>
<?php if ($tour->tourPrice->data->priceType == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) { ?>
            jQuery('.ghc').on('keypress', function () {
                return false;
            });
            jQuery('.ghc').spinner({
                min: 1,
                icons: {down: "ui-icon-minusthick", up: "ui-icon-plusthick"},
            });
            jQuery('.ghc').on('spin', function (event, ui) {
                var amount = <?php echo $tour->tourPrice->getPrice(TRUE); ?>;
                jQuery('#sp_hidghc').val(ui.value * amount);
            });
            jQuery('.ghc').on('spinstop', function (event, ui) {
                var totalAmount = 0;
                totalAmount = parseInt(totalAmount) + parseInt(jQuery('#sp_hidghc').val());
    <?php if ($tour->tourOptions->count() > 0) { ?>
                    jQuery('input[name^="tour_opt"]').each(function (i, el) {
                        if (jQuery(el).is(':checked')) {
                            var prType = jQuery(el).attr('prtype');
                            var prAmount = jQuery(el).val();
                            switch (prType) {
                                case '<?php echo \Tourpage\Models\ToursOptions::OPTION_PER_PERSON_CODE; ?>':
                                    var headCount = 0, headCountTotal = 0;
                                    var hc = jQuery('input[name="group_head_count"]').val();
                                    headCount = parseInt(headCount) + parseInt(hc);
                                    headCountTotal = headCount * prAmount;
                                    totalAmount = parseInt(totalAmount) + parseInt(headCountTotal);
                                    break;
                                case '<?php echo \Tourpage\Models\ToursOptions::OPTION_PER_GROUP_CODE; ?>':
                                    var headCountTotal = jQuery(el).val();
                                    totalAmount = parseInt(totalAmount) + parseInt(headCountTotal);
                                    break;
                            }
                        }
                    });
    <?php } ?>
                jQuery('#total_amount').attr('org', totalAmount);
                if (typeof discountPrecentage !== 'undefined') {
                    totalAmount = totalAmount - ((totalAmount * discountPrecentage) / 100);
                }
                if (typeof discountMultiplePurches !== 'undefined') {
                    var headCount = 0;
                    var hc = jQuery('input[name="group_head_count"]').val();
                    headCount = parseInt(headCount) + parseInt(hc);
                    if (headCount >= discountMultiplePurches.count) {
                        totalAmount = totalAmount - ((totalAmount * discountMultiplePurches.precentage) / 100);
                    }
                }
                jQuery('span#amount').html(formatMoney(totalAmount))
                jQuery('#total_amount').val(totalAmount);
            });

<?php } ?>
        jQuery('a#tour_tc').on('click', function (event) {
            event.preventDefault();
            jQuery('#model-tour-tc').modal();
        });
    });
    function addPriceopp(el, gd) {
        if (typeof gd === 'undefined') {
            gd = false;
        }
        var headCount = 0, headCountTotal = 0;
        var totalAmount = jQuery('#total_amount').attr('org');
<?php if ($tour->tourPrice->data->priceType == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_PERSON_CODE) { ?>
            for (var k in groupKeys) {
                var hc = jQuery('input[name="head_count[' + groupKeys[k] + ']"]').val();
                headCount = parseInt(headCount) + parseInt(hc);
            }
<?php } ?>
<?php if ($tour->tourPrice->data->priceType == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) { ?>
            var hc = jQuery('input[name="group_head_count"]').val();
            headCount = parseInt(headCount) + parseInt(hc);
<?php } ?>
        headCountTotal = headCount * el.value;
        if (el.checked) {
            totalAmount = parseInt(totalAmount) + parseInt(headCountTotal);
        } else {
            totalAmount = parseInt(totalAmount) - parseInt(headCountTotal);
        }
        if (!gd) {
            jQuery('#total_amount').attr('org', totalAmount);
            if (typeof discountPrecentage !== 'undefined') {
                totalAmount = totalAmount - ((totalAmount * discountPrecentage) / 100);
            }
            if (typeof discountMultiplePurches !== 'undefined') {
                var headCount = 0;
                for (var k in groupKeys) {
                    var hc = jQuery('input[name="head_count[' + groupKeys[k] + ']"]').val();
                    headCount = parseInt(headCount) + parseInt(hc);
                }
                if (headCount >= discountMultiplePurches.count) {
                    totalAmount = totalAmount - ((totalAmount * discountMultiplePurches.precentage) / 100);
                }
            }
            jQuery('span#amount').html(formatMoney(totalAmount))
            jQuery('#total_amount').val(totalAmount);
        } else {
            return totalAmount;
        }
    }
    function addPriceopg(el) {
        var totalAmount = jQuery('#total_amount').attr('org');
        var headCountTotal = el.value;
        if (el.checked) {
            totalAmount = parseInt(totalAmount) + parseInt(headCountTotal);
        } else {
            totalAmount = parseInt(totalAmount) - parseInt(headCountTotal);
        }
        jQuery('#total_amount').attr('org', totalAmount);
        if (typeof discountPrecentage !== 'undefined') {
            totalAmount = totalAmount - ((totalAmount * discountPrecentage) / 100);
        }
        if (typeof discountMultiplePurches !== 'undefined') {
            var headCount = 0;
            for (var k in groupKeys) {
                var hc = jQuery('input[name="head_count[' + groupKeys[k] + ']"]').val();
                headCount = parseInt(headCount) + parseInt(hc);
            }
            if (headCount >= discountMultiplePurches.count) {
                totalAmount = totalAmount - ((totalAmount * discountMultiplePurches.precentage) / 100);
            }
        }
        jQuery('span#amount').html(formatMoney(totalAmount))
        jQuery('#total_amount').val(totalAmount);
    }

<?php /* CKEDITOR.config.toolbarGroups = [
  {"name": "basicstyles", "groups": ["basicstyles"]},
  {"name": "paragraph", "groups": ["list"]},
  {"name": "styles", "groups": ["styles"]},
  ];
  CKEDITOR.config.removeButtons = 'Underline,Strike,Subscript,Superscript,Anchor,Styles,Specialchar';
  CKEDITOR.replace('rrtext', {
  "height": 150
  }); */ ?>
</script>
