<?php //\Tourpage\Helpers\Utils::printArray($formPostData, false);?>
<?php
$defaultPrice = 0;
if ($formPostData['tour_price_type'] == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_PERSON_CODE) {
	if (isset($formPostData['tour_age_group']) && isset($formPostData['tour_age_group']['a'])) {
		$defaultPrice = \Tourpage\Helpers\Utils::formatCurrency($formPostData['tour_age_group']['a']['price']);
	}
}
if ($formPostData['tour_price_type'] == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) {
	$defaultPrice = \Tourpage\Helpers\Utils::formatCurrency($formPostData['tour_price']);
}
?>

<div class="pdp">
	<div style="float:left;width:70%">
		<h3 style="font-size:20px;line-height:20px;color:#000"><?php echo isset($formPostData['tour_title']) ? $formPostData['tour_title'] : ''; ?></h3>
		<h5 style="font-size:14px;line-height:25px;color:#000"><?php echo isset($formPostData['tour_sub_title']) ? $formPostData['tour_sub_title'] : ''; ?></h5>
		<?php if (isset($formPostData['tour_image']) && count($formPostData['tour_image']['code']) > 0) { ?>
			<div id="store-ad" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					<?php for ($b = 0; $b < count($formPostData['tour_image']['code']); $b++) { ?>
						<li data-target="#store-ad" data-slide-to="<?php echo $b; ?>"<?php echo $b == 0 ? ' class="active"' : ''; ?>></li>
					<?php } ?>
				</ol>
				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<?php
					$c = 1;
					foreach ($formPostData['tour_image']['code'] as $tourImage) {
						?>
						<div class="item<?php echo $c == 1 ? ' active' : ''; ?>">
							<img src="<?php echo $tourImage; ?>" style="width: 1405px; height: 400px;">
						</div>
						<?php
						$c++;
					}
					?>
				</div>
				<!-- Controls -->
				<a class="left carousel-control" href="#store-ad" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#store-ad" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		<?php } ?>
		<?php if (isset($formPostData['tour_key_highlight']) && count($formPostData['tour_key_highlight']) > 0) { ?>
			<div class="desc-section">
				<ul class="list-unstyled">
					<?php foreach ($formPostData['tour_key_highlight'] as $tourKeyHighlight) { ?>
						<li><img style="width: 20px;hright: 20px;" src="<?php echo $tourKeyHighlight->getIconUri(); ?>"> <?php echo $tourKeyHighlight->keyhighlightTitle; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if (isset($formPostData['tour_details']) && count($formPostData['tour_details']) > 0) { ?>
			<div class="desc-section">
				<?php foreach ($formPostData['tour_details'] as $tourAttribute) { ?>
					<?php if ($tourAttribute['content'] != '') { ?>
						<h2><?php echo $tourAttribute['name']; ?></h2>
						<div style="border-bottom:1px solid #e8e8e8;margin-bottom: 10px;margin-left: 10px;">
							<?php echo \Tourpage\Helpers\Utils::decodeString($tourAttribute['content']); ?>
						</div>
					<?php } ?>
				<?php } ?>
			</div>
		<?php } ?>
	</div>
	<div style="float: left;width: 29%;margin-left: 7px;">
		<h2 style="margin-top: 21px;padding-left: 0;">Book This Tour Now</h2>
		<div class="booking-section">
			<div class="rightbox">
				<div class="info">
					<h2>Operator of this tour:</h2>
					<figure class="line-color">
						<?php
						$vendorAvator = $this->url->getStatic(FRONT_END_DIR . 'images/no_face.png');
						if ($formPostData['vendor']->getAvatarUri()) {
							$vendorAvator = $formPostData['vendor']->getAvatarUri();
						}
						echo $this->tag->image(array(
							$vendorAvator,
							"alt" => $formPostData['vendor']->getName(),
							"title" => $formPostData['vendor']->getName(),
							"width" => 80,
							"height" => 80
						));
						?>
					</figure>
					<ul class="info">
						<li class="name"><?php echo $this->tag->linkTo(array($formPostData['vendor']->getStorFrontUri(), $formPostData['vendor']->businessName, 'local' => false)); ?></li>
						<?php if ($formPostData['vendor']->estd) { ?>
							<li class="since">Established since <?php echo $formPostData['vendor']->estd; ?></li>
						<?php } ?>
						<li class="name">Operator: <?php echo $formPostData['vendor']->getName(); ?></li>
						<li class="location">Location: <?php echo ($formPostData['vendor']->state ? $formPostData['vendor']->state->name . ', ' : '') . ($formPostData['vendor']->country ? $formPostData['vendor']->country->name : ''); ?></li>
						<li class="name">Email: <?php echo $formPostData['vendor']->emailAddress; ?></li>
						<?php if ($formPostData['vendor']->phone) { ?>
							<li class="name">Phone: <?php echo $formPostData['vendor']->phone; ?></li>
						<?php } ?>
					</ul>
					<p class="clearboth"></p>
				</div>
			</div>
			<p class="clearboth"></p>
			<form id="tour_booking_form" method="post">
				<input type="hidden" name="form_action" value="booking">
				<ul>
					<li>From <div class="tour-price">US<?php echo $defaultPrice; ?></div> <?php echo $formPostData['tour_price_type_text']; ?></li>
					<?php if (isset($formPostData['lmd_duration']) && !empty($formPostData['lmd_duration'])) { ?>
						<li><em>(for <?php echo $formPostData['lmd_duration']; ?>days <?php echo ($formPostData['lmd_duration'] - 1); ?>nights)</em></li>
					<?php } ?>
					<?php if (isset($formPostData['tour_discount']) && !empty($formPostData['tour_discount']) && $formPostData['tour_discount'] > 0) { ?>
						<li>
							<div class="alert alert-info"><strong><?php echo $formPostData['tour_discount']; ?>% Discount</strong> From <?php echo $formPostData['tour_discount_start']; ?> To <?php echo $formPostData['tour_discount_end']; ?></div>
						</li>
					<?php } ?>
					<?php if (isset($formPostData['tour_mp_discount']) && !empty($formPostData['tour_mp_discount']) && $formPostData['tour_mp_discount'] > 0) { ?>
						<?php
						$headCountUnit = ' Person(s)';
						if ($formPostData['tour_price_type'] == \Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) {
							$headCountUnit = ' Group(s)';
						}
						?>
						<li>
							<div class="alert alert-info">
								<strong><?php echo $formPostData['tour_mp_discount']; ?>% Discount</strong> if booked for <?php echo $formPostData['tour_mp_count']; ?> <?php echo $headCountUnit; ?>
							</div>
						</li>
					<?php } ?>

					<?php
					switch ($formPostData['tour_length']) {
						case \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE:
							?>
							<li>Choose your journey date <div id="bookingdatepicker"></div></li>
							<li id="jdpanel" style="display: none;">
								<hr />
								<div>Departure: <date id="st">________</date></div>
								<div>Arrival: <date id="ed">________</date></div>
								<input type="hidden" id="jstd" name="jstd">
								<input type="hidden" id="jedd" name="jedd">
							</li>
							<?php
							break;
						case \Tourpage\Models\Tours::LENGTH_FIXED_DAYS_CODE:
							?>
							<li>
								<div>Departure: <?php echo $formPostData['tour_start_date']; ?></div>
								<div>Arrival: <?php echo $formPostData['tour_end_date']; ?></div>
								<input type="hidden" id="jstd" name="jstd" value="<?php echo $formPostData['tour_start_date']; ?>">
								<input type="hidden" id="jedd" name="jedd" value="<?php echo $formPostData['tour_end_date']; ?>">
							</li>
							<?php
							break;
						case \Tourpage\Models\Tours::LENGTH_SINGLE_DAY_CODE:
							?>
							<li>Choose your journey date <div id="bookingdatepicker"></div></li>
							<li id="jdpanel" style="display: none;">
								<hr />
								<div>Choosen Date: <date id="st">________</date></div>
								<input type="hidden" id="jstd" name="jstd">
							</li>
							<?php
							break;
						case \Tourpage\Models\Tours::LENGTH_HOURLY:
							?>
							<li>Choose your journey date <div id="bookingdatepicker"></div></li>
							<li id="jdpanel" style="display: none;">
								<hr />
								<div>Choosen Date: <date id="st">________</date></div>
								<input type="hidden" id="jstd" name="jstd">
							</li>
							<?php break; ?>
					<?php } ?>
				</ul>
				<?php if (isset($formPostData['tour_option']) && count($formPostData['tour_option']) > 0) { ?>
					<hr />
					<h3>Other Options</h3>
					<ul>
						<?php foreach ($formPostData['tour_option'] as $tourOptionIndex => $tourOption) { ?>
							<li><input name="tour_opt[<?php echo ($tourOptionIndex + 1);?>]" type="checkbox" value="<?php echo $tourOption['price']; ?>" onclick="addPrice<?php echo $tourOption['price_type']; ?>(this);" prtype="<?php echo $tourOption['price_type']; ?>"> <?php echo $tourOption['name'] . ' ' . \Tourpage\Helpers\Utils::formatCurrency($tourOption['price']); ?></li>
						<?php } ?>
					</ul>
				<?php } ?>
				<ul>
					<hr />
					<?php if ($formPostData['tour_price_type'] == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_PERSON_CODE) { ?>
						<?php
						foreach (\Tourpage\Helpers\Utils::getVar('config_tour_age_group') as $groupKey => $groupTitle) {
							if (isset($formPostData['tour_age_group'][$groupKey])) {
								?>
								<li><?php echo $groupTitle . ' ( ' . $formPostData['tour_age_group'][$groupKey]['age_type'] . ' ' . $formPostData['tour_age_group'][$groupKey]['age'] . ' )'; ?>
									<input type="text" value="<?php echo $groupKey == 'a' ? 1 : 0; ?>" name="head_count[<?php echo $groupKey; ?>]" class="spiner hc <?php echo $groupKey; ?>">
									<input type="hidden" id="sp_hid<?php echo $groupKey; ?>" value="<?php echo $groupKey == 'a' ? $formPostData['tour_age_group'][$groupKey]['price'] : 0; ?>">
								</li>
								<?php
							}
						}
						?>
					<?php } ?>
					<?php if ($formPostData['tour_price_type'] == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) { ?>
						<li>
							Number of Group(s) <input type="text" value="1" min="1" name="group_head_count" size="10" class="spiner ghc">
							<input type="hidden" id="sp_hidghc" value="<?php echo $formPostData['tour_price']; ?>">
						</li>
					<?php } ?>
				</ul>
				<hr />
				<div class="total">
					<input type="hidden" name="total_amount" id="total_amount" value="<?php echo $defaultPrice; ?>" org="<?php echo $defaultPrice; ?>">
					Total: US<span id="amount"><?php echo $defaultPrice; ?></span>
				</div>
				
				<hr />
				<button id="tour_booking_submit" class="btn btn-primary"><i class="fa fa-book"></i> Book now</button>
				<a id="tour_add_to_fav" class="btn btn-danger" onclick="alert('Preview Only'); return false;"><i class="fa fa-heart"></i> Add to favorite</a>

			</form>
		</div>
	</div>
</div>
<div style="clear:both;"></div>
<?php echo $this->tag->stylesheetLink($this->url->getStatic(FRONT_END_DIR . "css/style.css")); ?>
<style>
    .pdp {font-size:14px;line-height:24px;}
    .pdp h2{padding:10px;font-size:15px;font-weight:bold}
    .pdp ul{list-style:none}
    .pdp h3{margin-top:20px;}
    .pdp h4{margin-top:20px;}
    h4.modal-title{margin:0}
    .tour-price{display: inline;font-size: 24px;font-weight: bold;}
    .booking-section, .desc-section{/*border: 1px solid #9e9e9e;*/padding: 10px;margin-top: 7px;width: 100%;}
    .hasDatepicker{margin-bottom: 10px;}
    a.ui-datepicker-selected-bg, .ui-state-active{border-color: #ff0000 !important;color: #ff0000 !important;}
    .ui-datepicker td span, .ui-datepicker td a{text-align: center;}
    span.ui-state-default{cursor: not-allowed;}
    span.ui-spinner{height: 25px;margin-bottom: 10px;width: 70px;}
    input[type="text"].spiner{height: 30px;margin: 0;padding: 0 0 0 30px;width: 100%;}
    a.ui-spinner-down{left: 0;}
    .ui-spinner a.ui-spinner-button{border: none;top: 6px;cursor: pointer;}
    .btn-pad{padding: 6px 12px 6px 40px;}
    div.total{font-size: 24px;font-weight: bold;margin-bottom: 10px;}
    div.availibility p{margin-bottom: 0px;}
    .ui-widget-content{width: 100%;}
    .link_tc{cursor:pointer;}.modal-dialog{margin-top:100px;}
    form#tour_booking_form{padding:10px}
    .rightbox{width: 100%;}
    .rightbox .info{background: none; padding-top: 0;}
    .from-vendor, .from-category{width: 100%;margin-top: 7px;/*padding: 10px;*/}
    .from-vendor .from-vendor-item, .from-category .from-category-item{/*border: 1px solid #e8e8e8;padding: 5px;margin-right:15px;*/}
    .from-vendor .from-vendor-item ol li, .from-category .from-category-item ol li{list-style: none;}
    .more-item{padding-left:0; padding-right:0;}
    .reivewForm{list-style:none;float:left;width:100%}
    .reivewForm li label{display:inline-block;width:100px}
    .reivewForm li{text-align:left}
    .review-form{padding:10px;width: 100%;}
    .review-section{width: 100%;}
    .left-box-control {margin-top:-70px !important}
    .jumbotron {padding-left: 48px;padding-right: 48px;}
</style>
<script type="text/javascript">
    var disableDates = [];
    var accissableWeekDays = [<?php echo isset($formPostData['tour_week_days']) && count($formPostData['tour_week_days']) > 0 ? implode(',', $formPostData['tour_week_days']) : ''; ?>];
    var currentDate = new Date();
    var startDate = new Date('<?php echo $formPostData['tour_start_date'] ? $formPostData['tour_start_date'] : ''; ?>');
    var endDate = new Date('<?php echo $formPostData['tour_end_date'] ? $formPostData['tour_end_date'] : ''; ?>');
    var checkAvailState = false;
    var cacheData = {};
    if (currentDate >= startDate) {
        startDate = currentDate;
    }

<?php
$groupKeys = array_keys($formPostData['tour_age_group']);
$gks = '';
if (count($groupKeys) > 0) {
    foreach ($groupKeys as $gk) {
        $gks .= '"' . $gk . '",';
    }
}
$gks = (substr($gks, -1) == ',' ? substr($gks, 0, -1) : $gks);
echo 'var groupKeys = [' . $gks . '];';
?>
    jQuery(function () {
        

        

        jQuery('button#tour_booking_submit').on('click', function (event) {
            event.preventDefault();
            alert('Preview Only');
        });
        jQuery('#bookingdatepicker').datepicker({
            //changeMonth: true,
            //changeYear: true,
            //showOtherMonths: true,
            minDate: startDate,
            maxDate: endDate,
            beforeShowDay: function (d) {
                var accissableDay = true;
                if (jQuery.inArray(d.getDay(), accissableWeekDays) === -1) {
                    var datePickerDateString = jQuery.datepicker.formatDate('mm/dd/yy', d);
                    datePickerDateString = new Date(datePickerDateString).toLocaleDateString("en-US");
                    var dateString = datePickerDateString.split('/');
                    datePickerDateString = padInt(dateString[0]) + '/' + padInt(dateString[1]) + '/' + dateString[2];
                    accissableDay = false;
                    disableDates.push(datePickerDateString);
                }
                <?php
                switch ($formPostData['tour_length']) {
                    case \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE:
                    case \Tourpage\Models\Tours::LENGTH_FIXED_DAYS_CODE:
                    case \Tourpage\Models\Tours::LENGTH_SINGLE_DAY_CODE:
                        ?>
                        if (d.getDate() === currentDate.getDate() && d.getMonth() === currentDate.getMonth()) {
                            accissableDay = false;
                        }
                        <?php break; ?>
                <?php } ?>
                return [accissableDay];
            },
            onSelect: function (dateText, dp) {
                setTimeout(function () {
                    <?php
                    switch ($formPostData['tour_length']) {
                        case \Tourpage\Models\Tours::LENGTH_MULTIPLE_DAYS_CODE:
                            ?>
                            var std = jQuery('#bookingdatepicker').datepicker("getDate");
                            var totalDates = betweenDates(std, endDate);
                            if (totalDates.length >= totalDays) {
                                var edd = new Date(std.getFullYear(), std.getMonth(), std.getDate() + (totalDays - 1));
                                if (!jQuery('#jdpanel').is(':visible')) {
                                    jQuery('#jdpanel').show('slow');
                                }
                                jQuery('#st').html(std.toLocaleDateString("en-US"));
                                jQuery('#ed').html(edd.toLocaleDateString("en-US"));
                                jQuery('#jstd').val(std.toLocaleDateString("en-US"));
                                jQuery('#jedd').val(edd.toLocaleDateString("en-US"));
                            } else {
                                alert('Booking not available on ' + dateText);
                            }
                            <?php
                            break;
                        case \Tourpage\Models\Tours::LENGTH_SINGLE_DAY_CODE:
                        case \Tourpage\Models\Tours::LENGTH_HOURLY:
                            ?>
                            var std = jQuery('#bookingdatepicker').datepicker("getDate");
                            if (!jQuery('#jdpanel').is(':visible')) {
                                jQuery('#jdpanel').show('slow');
                            }
                            jQuery('#st').html(std.toLocaleDateString("en-US"));
                            jQuery('#jstd').val(std.toLocaleDateString("en-US"));
                            <?php break; ?>
                    <?php } ?>
                }, 5);
            }
        });
<?php if ($formPostData['tour_price_type'] == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_PERSON_CODE) { ?>
    <?php foreach (\Tourpage\Helpers\Utils::getVar('config_tour_age_group') as $groupKey => $groupTitle) { ?>
        <?php if (isset($formPostData['tour_age_group'][$groupKey])) { ?>
                    jQuery('.<?php echo $groupKey; ?>').on('keypress', function () {
                        return false;
                    });
                    jQuery('.<?php echo $groupKey; ?>').spinner({
                        min: <?php echo $groupKey == 'a' ? 1 : 0; ?>,
                        icons: {down: "ui-icon-minusthick", up: "ui-icon-plusthick"},
                    });
                    jQuery('.<?php echo $groupKey; ?>').on('spin', function (event, ui) {
                        var amount = <?php echo $formPostData['tour_age_group'][$groupKey]['price']; ?>;
                        jQuery('#sp_hid<?php echo $groupKey; ?>').val(ui.value * amount);
                    });
                    jQuery('.<?php echo $groupKey; ?>').on('spinstop', function (event, ui) {
                        var totalAmount = 0;
                        for (var k in groupKeys) {
                            totalAmount = parseInt(totalAmount) + parseInt(jQuery('#sp_hid' + groupKeys[k]).val());
                        }
            
                        jQuery('#total_amount').attr('org', totalAmount);
                        if (typeof discountPrecentage !== 'undefined') {
                            totalAmount = totalAmount - ((totalAmount * discountPrecentage) / 100);
                        }
                        if (typeof discountMultiplePurches !== 'undefined') {
                            var headCount = 0;
                            for (var k in groupKeys) {
                                var hc = jQuery('input[name="head_count[' + groupKeys[k] + ']"]').val();
                                headCount = parseInt(headCount) + parseInt(hc);
                            }
                            if (headCount >= discountMultiplePurches.count) {
                                totalAmount = totalAmount - ((totalAmount * discountMultiplePurches.precentage) / 100);
                            }
                        }
                        jQuery('span#amount').html(formatMoney(totalAmount))
                        jQuery('#total_amount').val(totalAmount);
                    });
        <?php } ?>
    <?php } ?>
<?php } ?>
<?php if ($formPostData['tour_price_type'] == Tourpage\Models\ToursPrice::PRICE_TYPE_PER_GROUP_CODE) { ?>
            jQuery('.ghc').on('keypress', function () {
                return false;
            });
            jQuery('.ghc').spinner({
                min: 1,
                icons: {down: "ui-icon-minusthick", up: "ui-icon-plusthick"},
            });
            jQuery('.ghc').on('spin', function (event, ui) {
                var amount = <?php echo $formPostData['tour_price']; ?>;
                jQuery('#sp_hidghc').val(ui.value * amount);
            });
            jQuery('.ghc').on('spinstop', function (event, ui) {
                var totalAmount = 0;
                totalAmount = parseInt(totalAmount) + parseInt(jQuery('#sp_hidghc').val());
    
                jQuery('#total_amount').attr('org', totalAmount);
                if (typeof discountPrecentage !== 'undefined') {
                    totalAmount = totalAmount - ((totalAmount * discountPrecentage) / 100);
                }
                if (typeof discountMultiplePurches !== 'undefined') {
                    var headCount = 0;
                    var hc = jQuery('input[name="group_head_count"]').val();
                    headCount = parseInt(headCount) + parseInt(hc);
                    if (headCount >= discountMultiplePurches.count) {
                        totalAmount = totalAmount - ((totalAmount * discountMultiplePurches.precentage) / 100);
                    }
                }
                jQuery('span#amount').html(formatMoney(totalAmount))
                jQuery('#total_amount').val(totalAmount);
            });

<?php } ?>
        
    });
    function addPriceopp(el, gd) {
        return 0;
    }
    function addPriceopg(el) {
        return 0;
    }

</script>

