<?php $this->partial('account/common/travelpreference_sidebar'); ?>
<div class="layout contents">
	<h2><i class="glyphicon glyphicon-music"></i> Your Perfect Day</h2>
	<div class="account wideinfo">
	<ul>
	<li><label>What's your day job?</label><input type="text"></li>
	<li><label>What kind of traveler are you?</label><input type="text"></li>
	<li><label>What are your travel cravings?</label><textarea></textarea></li>
	<li><label>What are your best travel experiences?</label><textarea></textarea></li>
	<li><label>Anything else?</label><textarea></textarea></li>
	</ul>
	</div>
	<div class="lastcontent thebuttonlayout001">
	<a class="btn save" href="/store-detail.php">SAVE </a> <a class="btn cancel" href="/store-detail.php"> Remove </a> 
	</div>
</div>
