<?php $this->partial('settings/menu'); ?>
<div class="col-md-9">
    <div class="panel panel-danger">
        <div class="panel-heading">
            <i class="glyphicon glyphicon-film"></i> <?php echo $pageHeading; ?> <span class="badge"><?php echo $banners->count(); ?></span>
            <div class="pull-right">
                <a class="btn btn-danger btn-xs tooltips" href="<?php echo $this->url->get('/admin/settings/banner/ads/add/' . $type); ?>" role="button" title="Add New <?php echo $pageHeading; ?>">
                    <span class="glyphicon glyphicon-plus"></span> Add New <?php //echo $pageHeading;          ?>
                </a>
            </div>
        </div>
        <div class="panel-body">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Banner Image & Link</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($banners->count() > 0) { ?>
                        <?php foreach ($banners as $banner) { ?>
                            <tr>
                                <td>
                                    <?php
                                    echo $this->tag->image(array(
                                        $banner->getBannerUri(),
                                        'class' => 'img-thumbnail',
                                        'width' => 600
                                    ));
                                    ?>
                                    <?php if (!empty($banner->bannerLink)) { ?>
                                        <br />
                                        Link: <?php echo $this->tag->linkTo(array($banner->bannerLink, $banner->bannerLink, 'local' => false, 'target' => '_blank')); ?>
                                    <?php } ?>
                                </td>
                                <td><?php echo $banner->getStatus(); ?></td>
                                <td>
                                    <a title="" class="btn btn-primary btn-xs tooltips" href="<?php echo $this->url->get('/admin/settings/banner/ads/edit/' . $banner->bannerId . '/' . $type); ?>" data-original-title="Edit <?php echo $pageHeading; ?>"><span class="glyphicon glyphicon-pencil"></span></a>
                                    <a title="" class="btn btn-primary btn-xs tooltips" href="<?php echo $this->url->get('/admin/settings/banner/ads/remove/' . $banner->bannerId . '/' . $type); ?>" data-original-title="Remove <?php echo $pageHeading; ?>" onclick="if(!confirm('Are you sure?')) {return false;}"><span class="glyphicon glyphicon-remove"></span></a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

