<?php /*if ($banners && $banners->count() > 0) { ?>
    <?php /* <section id="HomepageSlideshowOuter" style="margin-top: 72px;">
      <section id="HomepageSlideshow" class="flexslider" style="width:100%;height:100%;">
      <ul class="slides" style="width:100%;height:100%;">
      <?php foreach ($banners as $banner) { ?>
      <li style="background:url('<?php echo $banner->getBannerUri(); ?>') no-repeat top center;background-size:auto 100%;width:100%;"></li>
      <?php } ?>
      </ul>
      </section>
      </section> *\/ ?>
    <div id="home-ad" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <?php for ($b = 0; $b < $banners->count(); $b++) { ?>
                <li data-target="#home-ad" data-slide-to="<?php echo $b; ?>"<?php echo $b == 0 ? ' class="active"' : ''; ?>></li>
            <?php } ?>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <?php $c = 1;
            foreach ($banners as $banner) { ?>
                <div class="item<?php echo $c == 1 ? ' active' : ''; ?>">
                        <?php if (!empty($banner->bannerLink)) { ?>
                        <a href="<?php echo $banner->bannerLink; ?>" target="_blank">
                        <?php } ?>
                        <img src="<?php echo $banner->getBannerUri(); ?>" alt="Home ad banner" style="width: 1405px; height: 400px;">
                    <?php if (!empty($banner->bannerLink)) { ?>
                        </a>
                <?php } ?>
                </div>
        <?php $c++;
        } ?>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#home-ad" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#home-ad" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <?php }*/ ?>
    <section class="dataoutputs">
    <?php if ($vendors && $vendors->count() > 0) { ?>
        <h2 class="title">Vendors</h2>
        <table class="list">
            <tr>
                <th align="left">Store Logo</th>
                <th align="left">Operator</th>
                <th align="left">Store front</th>
                <th align="left">Location</th>
            </tr>
                    <?php foreach ($vendors as $vendor) { ?>
                <tr>
                    <td>
                        <?php if ($vendor->getLogoUri()) { ?>
                            <?php echo $this->tag->image(array($vendor->getLogoUri(), "alt" => $vendor->businessName, "height" => 50, "width" => 50), false); ?>
                        <?php } else { ?>
                            Logo not found
                <?php } ?>
                    </td>
                    <td><?php echo $vendor->firstName . ' ' . $vendor->lastName; ?></td>
                    <td><?php echo $this->tag->linkTo(array($vendor->getStorFrontUri(), $vendor->businessName, 'local' => false)); ?></td>
                    <td>
                        <?php if ($vendor->city !="") { ?>
                        <?php echo $vendor->city . ', '; }?><?php if ($vendor->state !="") { echo $vendor->state->name . ', ';}?><?php if ($vendor->country !="") { echo $vendor->country->name; }?>
                         
                    </td>
                </tr>
        <?php } ?>
        </table>
        <?php } ?>
        <?php if ($vendorTours && $vendorTours->count() > 0) { ?>
        <h2 class="title">Tours</h2>
        <table class="list">
            <tr>
                <th align="left">Image</th>
                <th align="left">Tour</th>
                <th align="left">Owner</th>
                <th align="left">Tour Type</th>
                <th align="left">Price</th>
                <th align="left">Booking Status</th>
            </tr>
            <?php foreach ($vendorTours as $vendorTour) { ?>
                <tr>
                    <td>
                        <?php if ($vendorTour->tour->getDefaultImage()) { ?>
                            <a href="<?php echo $vendorTour->tour->getUri(); ?>">
                                <?php echo $this->tag->image(array($vendorTour->tour->getDefaultImage()->getImageUri('thumb'), "alt" => $vendorTour->tour->tourTitle, "height" => 50, "width" => 50), false); ?>
                            </a>
                        <?php } ?>
                    </td>
                    <td style="vertical-align:middle">
                    <?php echo $this->tag->linkTo(array($vendorTour->tour->getUri(), $vendorTour->tour->tourTitle, 'local' => false)); ?>
                        <br /><span style="font-size: 12px;"><?php echo $vendorTour->tour->tourSubTitle; ?></span>
                        <br /><span style="font-size: 12px;">Price type: <?php echo $vendorTour->tour->tourPrice->data->priceTypeText; ?></span>
                    </td>
                    <td style="vertical-align:middle">
                    <?php echo $this->tag->linkTo(array($vendorTour->vendor->getStorFrontUri(), $vendorTour->vendor->businessName, 'local' => false)); ?>
                        <br /><span style="font-size: 12px;">Operator: <?php echo $vendorTour->vendor->firstName . ' ' . $vendorTour->vendor->lastName; ?></span>
                    </td>
                    <td style="vertical-align:middle"><?php echo $vendorTour->tour->tourDuration->lengthTypeText; ?></td>
                    <td style="vertical-align:middle"><?php echo \Tourpage\Helpers\Utils::formatCurrency($vendorTour->tour->tourPrice->getPrice()); ?></td>
                    <td style="vertical-align:middle">
                        <?php if (!$vendorTour->tour->isBookingActive()) { ?>
                            <span class="label label-warning">Booking closed</span>
                        <?php } else { ?>
                            <a id="tour_booking_submit" class="btn btn-facebook btn-pad" href="<?php echo $vendorTour->tour->getUri(); ?>"><i class="fa fa-eye"></i> View now</a>
                <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </table>
<?php } ?>
</section>
<style>
    table.list {
        /*margin-left: 10px;*/
        margin-top: 10px;
        width: 100%;
    }
    table.list tr {
        border: 1px solid;
    }
    table.list tr, table.list td, table.list th {
        padding: 10px;
        font-size: 14px;
    }
    table.list td a:hover {
        text-decoration: underline;

    }
    h2.title{ 
        /*margin-left: 10px;*/
        margin-top: 30px;
    }
</style>
