<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-remove"></span> Remove Message
        </h3>
    </div>
    <div class="panel-body">
        <div class="page-header">
            <h2>Are you sure! you want to remove <small><i>"<?php echo $message->message->messageText; ?>"</i></small> ?</h2>
        </div>
        <div class="col-lg-4">
            <form method="post">
                <input type="hidden" name="key" value="<?php echo md5('confirm'); ?>" />
                <input type="hidden" name="messageId" value="<?php echo $message->messageId; ?>" />
                <input type="submit" name="submit" class="btn btn-danger" value="Remove" />
                <?php echo $this->tag->linkTo(array('/admin/message/index', 'Back', 'class' => 'btn btn-primary')); ?>
            </form>
        </div>
    </div>
</div>
