<?php
if (isset($storeVendor) && $storeVendor) {
	$address = $infowindowContent = '';
	if (!empty($storeVendor->city)) {
		$address .= $storeVendor->city . ',';
	}
	if ($storeVendor->state) {
		$address .= $storeVendor->state->name . ',';
	}
	if ($storeVendor->country) {
		$address .= $storeVendor->country->name . ',';
	}
	$location = \Tourpage\Helpers\Utils::getGeolocation($address);
	$vendorAvator = $this->url->getStatic(FRONT_END_DIR . 'images/no_face.png');
	if ($storeVendor->getAvatarUri()) {
		$vendorAvator = $storeVendor->getAvatarUri();
	}
	
	$infowindowContent .= '<div style="width:300px;min-height:120px;">';
	$infowindowContent .= '<div style="width:120px;float:left;">';
	$infowindowContent .= $this->tag->image(array(
		$vendorAvator,
		"alt" => $storeVendor->firstName,
		"title" => $storeVendor->firstName,
		"width" => 120,
		"height" => 120
	));
	$infowindowContent .= '</div>';
	$infowindowContent .= '<div style="width:170px;float:left;margin-left: 10px;">';
	$infowindowContent .= '<ul>';
	$infowindowContent .= '<li style="font-size:20px;margin-bottom: 5px;font-weight: bold;">' . $storeVendor->businessName . '</li>';
	if ($storeVendor->estd) {
		$infowindowContent .= '<li style="margin-bottom: 5px;">Established since ' . $storeVendor->estd . '</li>';
	}
	$infowindowContent .= '<li style="margin-bottom: 5px;">Operator: ' . $storeVendor->getName() . '</li>';
	$infowindowContent .= '<li style="margin-bottom: 5px;"><i class="fa fa-building"></i> ' . $address . '</li>';
	$infowindowContent .= '<li style="margin-bottom: 5px;"><i class="fa fa-envelope"></i> ' . $storeVendor->emailAddress . '</li>';
	if ($storeVendor->phone) {
		$infowindowContent .= '<li style="margin-bottom: 5px;"><i class="fa fa-phone"></i> ' . $storeVendor->phone . '</li>';
	}
	$infowindowContent .= '</ul>';
	$infowindowContent .= '</div>';
	$infowindowContent .= '</div>';
	
?>
<!--<div id="map" style="width:100%;height:350px;margin-top: 20px;"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQc2RC2E2C7SgUoML9D-Q-VMUt7Q6fEhA"></script>-->
<script type="text/javascript">
	/*function initializeMap() {
		var mapCenter = {
			lat : <?php //echo $location->lat;?>,
			lng : <?php //echo $location->lng . "\n";?>
		};
		var mapOptions = {
			zoom: 15,
			scrollwheel: false,
			center: new google.maps.LatLng(mapCenter.lat, mapCenter.lng),
			overviewMapControl: true,
			overviewMapControlOptions: {
				opened: true,
			},
		};
		var map = new google.maps.Map(document.getElementById('map'),mapOptions);
		var infowindow = new google.maps.InfoWindow({
			maxWidth: 300
		});
		var marker = new google.maps.Marker({
			position: new google.maps.LatLng(mapCenter.lat, mapCenter.lng),
			map: map,
		});
		google.maps.event.addListener(marker, 'click', (function(marker) {
			return function() {
				infowindow.setContent('<?php echo $infowindowContent;?>');
				infowindow.open(map, marker);
			}
		})(marker));
	}
	google.maps.event.addDomListener(window, 'load', initializeMap);*/
</script>
<?php } ?>
<footer class="footer">
	<div class="container">
		<div class="row">
        <div class="col-sm-12">
			<div class="col-sm-3">
				<h4>Contacts</h4>
				<p>112 42nd Street, New York NY, 10021</p>
				<p>+12 1234 1212 / 215 454 4455</p>
				<p><a href="#">info@tourpage.net</a></p>
			</div>
			<?php /*<ul class="footerList">
				<li class="title">Best Tours</li>
				<?php if ($storeVendor->vendorTours->count() > 0) { ?>
					<?php foreach ($storeVendor->vendorTours as $vendorTour) { ?>
						<li><a href="<?php echo $vendorTour->tour->getUri();?>">- <?php echo $vendorTour->tour->tourTitle; ?></a></li>
					<?php } ?>
				<?php } ?>
			</ul>*/?>
			<div class="col-sm-3">
				<h4>About</h4>
				<ul class="footer-link">
					<li><a href="#">About Viator Tour Guides</a></li>
					<li><a href="#">Tour Guide Register</a></li>
					<li><a href="#">Sitemap</a></li>
					<li><a href="#">Privacy</a></li>
					<li><a href="#">T&amp;C’s</a></li>
					<li><a href="#">FAQ</a></li>
				</ul>
			</div>
			<div class="col-sm-3">
				<h4>To be Tourpage Member</h4>
				<ul class="footer-link">
					<li><a href="#">About Viator Tour Guides</a></li>
					<li><a href="#">Tour Guide Register</a></li>
					<li><a href="#">Sitemap</a></li>
					<li><a href="#">Privacy</a></li>
					<li><a href="#">T&amp;C’s</a></li>
					<li><a href="#">FAQ</a></li>
				</ul>
			</div>
			<div class="col-sm-3">
				<h4>Newsletter</h4>
				<p>Join out newsletter to keep be informed about offers and news.</p>
				<div class="input-group">
					<input type="text" class="form-control" placeholder="you@example.com">
					<span class="input-group-btn">
					  <button class="btn btn-info btn-flat" type="button">JOIN US</button>
					</span>
				</div>
			</div>
		</div>
		<br><br>
		<div class="text-center">
			<p><?php echo \Tourpage\Helpers\Utils::__getCurrentYear();?> &copy; Tourpage, Inc. All rights reserved. Tourpage is a registered trademark of Tourpage, Inc.</p>
		</div>
	</div>
    </div>
</footer>
<style>.footer{background:#1f5f7a;}.footer-link{line-height:20px;}</style>

