<?php echo $this->tag->stylesheetLink($this->url->getStatic(COMMON_DIR . "css/dropzone.css")); ?>
<?php echo $this->tag->stylesheetLink($this->url->getStatic(COMMON_DIR . "css/slimNav_sk78.css")); ?>
<?php echo $this->tag->stylesheetLink($this->url->getStatic(COMMON_DIR . "css/colorbox.css")); ?>
<!-- REMOVE DROPZONE BORDER -->
<style>
	.dropzone {
		border: none !important;
	}
</style>
<?php $this->partial('account/common/reviews_sidebar'); ?>
<div class="layout contents">
    <h2>
        <?php if ($reviewType == 'pending') { ?>
            <i class="glyphicon glyphicon-pencil"></i> Pending review <span>(<?php echo $pager->getTotalItems(); ?>)</span>
        <?php } ?>
        <?php if ($reviewType == 'confirmed') { ?>
            <i class="glyphicon glyphicon-sunglasses"></i> Confirmed review <span>(<?php echo $pager->getTotalItems(); ?>)</span>
        <?php } ?>
		<?php if ($reviewType == 'new') { ?>
            <i class="glyphicon glyphicon-plus"></i> Add new review
        <?php } ?>
    </h2>
    <div class="account column1">
		<?php if ($reviewType == 'new'): ?>
		<!-- ADD NEW REVIEW START -->
		<form action="/account/addReview" method="post" id="gallery-form">
		<input type="hidden" name="rate" id="star-rate">
		<input type="hidden" name="vendor" id="vendor">
		<div class="item">
			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<label class="label-10">Select Your Tour</label><br>
						<select name="tour" class="form-control" required="required" onchange="onTourChange(this)">
							<option value=''>-- select tour --</option>
							<?php foreach($membersTours['title'] as $k => $tours): ?>
								<option vendor="<?php echo $membersTours['vendorId'][$k]; ?>" value="<?php echo $membersTours['tourId'][$k]; ?>"><?php echo $tours ?></option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
				<div class="clear-fixed"></div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<label class="label-10">Review</label><br>
						<textarea class="form-control" rows="10" required="required" name="review"></textarea>
					</div>
				</div>
				<div class="clear-fixed"></div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<label class="label-10">Star Rate</label><br>
						<ul class="review">
							<li class="text-yellow">
								<div id="star-rate-box"></div>
								<script>
									jQuery(function () {
									jQuery('#star-rate-box').rateYo({rating: 0, starWidth: "15px", readOnly: false, ratedFill: "#ede811", onSet: function (rating, rateYoInstance) {
		$("#star-rate").val(rating);
    }});
								});</script>
							</li>
						</ul>
					</div>
				</div>
				<div class="clear-fixed"></div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<!-- FILES UPLOAD START -->
					<div class="list-group">
						<div class="list-group-item">
							<div class="row" id="actions">
								<div class="col-lg-7">
									<span class="btn btn-success fileinput-button"><i class="glyphicon glyphicon-plus"></i> <span>Add Photos / Images</span></span>
									<button class="btn btn-primary start" type="submit" style="display:none;"><i class="glyphicon glyphicon-upload"></i> <span>Start upload</span></button>
									<button class="btn btn-warning cancel" type="reset" style="display:none;"><i class="glyphicon glyphicon-ban-circle"></i> <span>Cancel upload</span></button>
								</div>
							</div>
						</div>
						<input type="hidden" name="action" value="">
						<div class="list-group-item" style="float: left; width: 100%">
							<!-- start dropzone -->
							<div class="dropzone" id="dropzone">
								<div id="previews" class="table table-striped">
										<div class="dz-message">
												Drop files here or click to "Add Photos / Images" button. Accepted file types are image/jpeg, image/png<br>
											<span class="note">(This is just a drop zone. Selected files will <strong>not</strong> uploaded directly. Click the <strong>"Start upload"</strong> button to uploads the files and after that you need to click on <strong>"Submit"</strong> button below to save images for this review.)</span>
										</div>
								</div>
								<div class="table table-striped" class="files">
									<div id="template" class="file-row">
										<div class="col-sm-6 col-md-4">
											<input type="hidden" name="galleries[name][]" class="image_name">
											<input type="hidden" name="galleries[path][]" class="image_path">
											<input type="hidden" name="galleries[code][]" class="image_code">
								
											<div class="thumbnail">
												<span class="preview"><img alt="" data-dz-thumbnail></span>
												<div class="caption">
													<div>
														<p class="name col-sm-8 no-pad-left" data-dz-name></p>
														<p class="size col-sm-4 no-pad text-right" data-dz-size></p>
														<div class="clearfix"></div>
													</div>
													<div><strong class="error text-danger" data-dz-errormessage></strong></div>
													<div class="file_progress">
														<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
															<div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
														</div>
													</div>
													<div class="action_buttons">
														<button class="btn btn-primary start"><i class="glyphicon glyphicon-upload"></i> <span>Start</span></button>
														<button data-dz-remove class="btn btn-warning cancel"><i class="glyphicon glyphicon-ban-circle"></i> <span>Cancel</span></button>
														<button data-dz-remove class="btn btn-danger delete"><i class="glyphicon glyphicon-trash"></i> <span>Delete</span></button>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- IMAGE UPLOAD END -->
					</div>
					<br class="clearboth">
					</div>
				</div>
		</form>
		<div class="row">
			<div class="col-sm-12">
				<div class="form-group">
					<button name="submit" value="Add" class="btn btn-primary" id="save-photos">Submit</button>
				</div>
			</div>
			<div class="clear-fixed"></div>
		</div>
		<!-- END NEW REVIEW -->
		<?php else: ?>
        <?php if ($pager->getTotalItems() > 0) { ?>
            <?php foreach ($pager->getItems() as $review) { ?>
                <div class="item">
					<div class="image thumbnail">
                    
                    <?php if ($review->tour->getDefaultImage()) { ?>
						<a href="<?php echo $review->tour->getUri(); ?>">
							<?php echo $this->tag->image(array($review->tour->getDefaultImage()->getImageUri('thumb'), "alt" => $review->tour->tourTitle), false); ?>
						</a>
					<?php } ?>
					</div>
                    <div class="info">
                        <h1 style="margin-top: 0;"><?php echo $this->tag->linkTo(array($review->tour->getUri(), $review->tour->tourTitle, 'local' => false)); ?></h1>
                        <div class="left">
                            <div class="operator">
                                <?php
								$vendorAvator = $this->url->getStatic(FRONT_END_DIR . 'images/no_face.png');

								$storeVendor = \Tourpage\Models\Vendors::findFirst(array('tourId'=>$review->tour->tourId));
								/*if ($review->tour->tourVendor->vendor->getAvatarUri()) {*/
								if ($storeVendor->getAvatarUri()) {
									/*$vendorAvator = $review->tour->tourVendor->vendor->getAvatarUri();*/
									$vendorAvator = $storeVendor->getAvatarUri();
								}
								echo $this->tag->image(array(
									$vendorAvator,
									"alt" => $storeVendor->firstName . $storeVendor->lastName,
									"title" => $storeVendor->firstName . $storeVendor->lastName,
									"width" => 55,
									"height" => 64
								));
								?>
                                <ul>
                                    <li class="companyname"><?php echo $this->tag->linkTo(array($storeVendor->getStorFrontUri(), $storeVendor->businessName, 'local' => false)); ?></li>
                                    <li class="additional">
										<span><i class="glyphicon glyphicon-map-marker"></i> <?php echo ($storeVendor->state ? $storeVendor->state->name . ', ' : '') . ($storeVendor->country ? $storeVendor->country->name : ''); ?></span><br />
										<?php if ($storeVendor->phone) { ?>
											<span><i class="glyphicon glyphicon-phone-alt"></i> <?php echo $storeVendor->phone; ?></span><br />
										<?php } ?>
										<span><i class="glyphicon glyphicon-envelope"></i> <?php echo $storeVendor->emailAddress; ?></span>
									</li>
                                </ul>
                            </div><!--//operator-->
                            <?php /*<ul class="add_info">
                                <li><?php echo \Tourpage\Helpers\Utils::formatDate($review->review->reviewOn, \Tourpage\Helpers\Utils::DATE_FORMAT_MEDIUM);?></li>
                                <li>(Opening/Operating Hours:10:00AM - 5:45 PM)</li>
                                <li>2XAdult (Age 13- 64)</li>
                            </ul>*/ ?>
                        </div><!--//left-->
                        <div class="right reviewLayout">
                            <div class="reviewInput">
                                <p class="rating"> Rating: <span id="star_count_<?php echo $review->reviewId;?>"></span></p>
                                <script>jQuery(function(){jQuery('#star_count_<?php echo $review->reviewId;?>').rateYo({rating: <?php echo $review->review->starCount;?>,starWidth: "20px",readOnly: true});});</script>
                                <p><?php echo \Tourpage\Helpers\Utils::decodeString($review->review->reviewContent);?></p>
                            </div><!--//reviewInput-->
                        </div><!--//right-->
                    </div><!--//info-->
                    <br class="clearboth">
					<!-- FILES UPLOAD START -->
					<div class="list-group">
						<?php if ($reviewType == 'pending'): ?>
						<div class="list-group-item">
							<div class="row" id="actions">
								<div class="col-lg-7">
									<span class="btn btn-success fileinput-button"><i class="glyphicon glyphicon-plus"></i> <span>Add Photos / Images</span></span>
									<button class="btn btn-primary start" type="submit" style="display:none;"><i class="glyphicon glyphicon-upload"></i> <span>Start upload</span></button>
									<button class="btn btn-warning cancel" type="reset" style="display:none;"><i class="glyphicon glyphicon-ban-circle"></i> <span>Cancel upload</span></button>
								</div>
							</div>
						</div>
						<?php endif; ?>
						<!-- FORM Action -->
						<form action="/account/gallery" method="post" id="gallery-form">
						<input type="hidden" name="action" value="<?php echo $reviewType; ?>">
						<div class="list-group-item" style="float: left; width: 100%">
							<!-- start dropzone -->
							<div class="dropzone" id="dropzone">
								<div id="previews" class="table table-striped">
									<?php if (count($gallery) > 0 ): ?>
										<?php if (isset($gallery[$review->reviewId])): ?>
											<?php foreach ($gallery[$review->reviewId]['image'] as $key => $item): ?>
												<div class="col-sm-6 col-md-4">
													<div class="thumbnail">
														<span class="preview">
															<?php if ($reviewType == 'confirmed'): ?>
																<a class="group1" href="<?php echo $item; ?>" title="">
																	<img src="<?php echo $item; ?>" style="height: 200px;" alt="">
																</a>
															<?php else: ?>
																<img src="<?php echo $item; ?>" style="height: 200px;" alt="">
															<?php endif; ?>
														</span>
														<?php if ($reviewType == 'confirmed'): ?>
															<div class="caption">
																<div class="action_buttons remove-img-checkbox-<?php echo $review->reviewId; ?>" style="display:none;">
																	<label style="font-size: 12px;float: left;"><input type="checkbox" name="remove_img[]" value="<?php echo $gallery[$review->reviewId]['galleryId'][$key]; ?>"/> Remove</label>
																	<div class="clearfix"></div>
																</div>
															</div>
														<?php endif; ?>
														<!--
														<div class="caption">
															<div class="action_buttons">
																<label style="font-size: 12px;float: left;"><input type="checkbox" name="remove_img[]" value="" /> Remove</label>
																<label style="font-size: 12px;float: right;"><input type="radio" name="default_img" value="" /> Default</label>
																<div class="clearfix"></div>
															</div>
														</div>
														-->
													</div>
												</div>
											<?php endforeach; ?>
										<?php endif; ?>
									<?php else: ?>
										<div class="dz-message">
											<?php if ($reviewType == 'pending'): ?>
												Drop files here or click to "Add Photos / Images" button. Accepted file types are image/jpeg, image/png<br>
											<span class="note">(This is just a drop zone. Selected files will <strong>not</strong> uploaded directly. Click the <strong>"Start upload"</strong> button to uploads the files and after that you need to click on <strong>"Save Photos / Images"</strong> button below to save images for this review.)</span>
											<?php else: ?>
												No Images uploaded
											<?php endif; ?>
										</div>
									<?php endif; ?>
								</div>
								<div class="table table-striped" class="files">
									<div id="template" class="file-row">
										<div class="col-sm-6 col-md-4">
											<input type="hidden" name="galleries[name][]" class="image_name">
											<input type="hidden" name="galleries[path][]" class="image_path">
											<input type="hidden" name="galleries[code][]" class="image_code">
											<input type="hidden" name="galleries[reviewId]" value="<?php echo $review->reviewId; ?>" class="">
											<input type="hidden" name="galleries[tourId]" value="<?php echo $review->tour->tourId; ?>">
											<input type="hidden" name="galleries[memberId]" value="<?php echo $memberId; ?>">
											<input type="hidden" name="galleries[vendorId]" value="<?php echo $review->review->vendorId; ?>">
											<div class="thumbnail">
												<span class="preview"><img alt="" data-dz-thumbnail></span>
												<div class="caption">
													<div>
														<p class="name col-sm-8 no-pad-left" data-dz-name></p>
														<p class="size col-sm-4 no-pad text-right" data-dz-size></p>
														<div class="clearfix"></div>
													</div>
													<div><strong class="error text-danger" data-dz-errormessage></strong></div>
													<div class="file_progress">
														<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
															<div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
														</div>
													</div>
													<div class="action_buttons">
														<button class="btn btn-primary start"><i class="glyphicon glyphicon-upload"></i> <span>Start</span></button>
														<button data-dz-remove class="btn btn-warning cancel"><i class="glyphicon glyphicon-ban-circle"></i> <span>Cancel</span></button>
														<button data-dz-remove class="btn btn-danger delete"><i class="glyphicon glyphicon-trash"></i> <span>Delete</span></button>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="clearboth" style="padding:15px 0px 15px 0px;">
						<!-- START HIDDEN EDIT REVIEW -->
						<?php if ($reviewType == 'confirmed'): ?>
							<div class="list-group-item review-form-<?php echo $review->review->reviewId; ?>" style="display:none;">
								<input type="hidden" name="reviewId" value="<?php echo $review->review->reviewId; ?>">
								<input type="hidden" name="star_rate" id="star-rate-edit-review-<?php echo $review->review->reviewId; ?>">
								<div class="row">
									<div class="col-sm-12">
										<div class="form-group">
											<label class="label-10">Review</label><br>
											<textarea class="form-control textarea-edit-review-<?php echo $review->review->reviewId; ?>" rows="10" required="required" name="review">
												<?php echo \Tourpage\Helpers\Utils::decodeString($review->review->reviewContent);?>
											</textarea>
										</div>
									</div>
									<div class="clear-fixed"></div>
								</div>
								<div class="row">
									<div class="col-sm-12">
										<div class="form-group">
											<label class="label-10">Star Rate</label><br>
											<ul class="review">
												<li class="text-yellow">
													<div id="star-rate-box-<?php echo $review->review->reviewId; ?>"></div>
													<script>
														jQuery(function () {
														jQuery('#star-rate-box-<?php echo $review->review->reviewId; ?>').rateYo({rating: <?php echo $review->review->starCount;?>, starWidth: "15px", readOnly: false, ratedFill: "#ede811", onSet: function (rating, rateYoInstance) {
							$("#star-rate-edit-review-<?php echo $review->review->reviewId; ?>").val(rating);
							}});
													});</script>
												</li>
											</ul>
										</div>
									</div>
									<div class="clear-fixed"></div>
								</div>
							</div>
						<?php endif; ?>
						<!-- END HIDDEN EDIT REVIEW FORM -->
						<div class="clearboth" style="padding:15px 0px 15px 0px;">
							<div class="row">
								<div class="col-lg-7">
									<span class="btn btn-primary" id="save-photos"><i class="glyphicon glyphicon-drop"></i> <span><?php if ($reviewType == 'pending') { ?>Save Photos / Images<?php } else { ?>Update Changes<?php } ?></span></span>
									<?php if ($reviewType == 'confirmed') { ?><span class="btn btn-warning edit-review" id="edit-review" review-id="<?php echo $review->review->reviewId; ?>"><i class="glyphicon glyphicon-drop"></i> <span>Edit Review</span></span>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
					<!-- IMAGE UPLOAD END -->
					</form>
					<br class="clearboth">
                </div>
</div>
            <?php } ?>
        <?php } else { ?>
            List is empty
        <?php } ?>
		<?php endif; ?>
	</div>
    <nav>
        <?php echo $pager->getLinks(); ?>
    </nav>
</div>
<style>.image a img{height:154px;}</style>

<?php echo $this->tag->javascriptInclude($this->url->getStatic(COMMON_DIR . "js/jquery.colorbox.js")); ?>
<!-- handles dropzone -->
<?php echo $this->tag->javascriptInclude($this->url->getStatic(COMMON_DIR . "js/dropzone.js")); ?>
<script>
$(".group1").colorbox({rel:'group1'});
$('#save-photos').click(function() {
	$('#gallery-form').submit();
});
$('.edit-review').click(function() {
	// trim textarea values whitespaces
	var textarea_edit_review = $('.textarea-edit-review-'+$(this).attr('review-id'));
	textarea_edit_review.val($.trim(textarea_edit_review.val()).replace(/\s*[\r\n]+\s*/g, '\n')
						   .replace(/(<[^\/][^>]*>)\s*/g, '$1')
						   .replace(/\s*(<\/[^>]+>)/g, '$1'));
	$('.remove-img-checkbox-'+$(this).attr('review-id')+', .review-form-'+$(this).attr('review-id')).css('display','block');
});
var previewNode = document.querySelector("#template");
previewNode.id = "";
var previewTemplate = previewNode.parentNode.innerHTML;
previewNode.parentNode.removeChild(previewNode);
var TourImage = new Dropzone('#dropzone', {
        url: "<?php echo $this->url->get('/ajax/sendFile'); ?>",
        acceptedFiles: 'image/jpeg,image/png',
        thumbnailWidth: 242,
        thumbnailHeight: 200,
        parallelUploads: 8,
        previewTemplate: previewTemplate,
        autoQueue: false,
        previewsContainer: "#previews",
        clickable: ".fileinput-button",
        dictDefaultMessage: ""
    });
    TourImage.on("addedfile", function (file) {
		hasNewImage = true;
        document.querySelector("#actions .cancel").removeAttribute("disabled");
		$('.dz-message').html('');
        file.previewElement.querySelector(".start").onclick = function () {
            TourImage.enqueueFile(file);
            return false;
        };
    });
	
    TourImage.on("thumbnail", function (file, dataUrl) {
        file.previewElement.querySelector(".image_code").value = dataUrl;
    });
    TourImage.on("sending", function (file, xhr, formData) {
        file.previewElement.querySelector(".start").setAttribute("disabled", "disabled");
    });
    TourImage.on("uploadprogress", function (file, progress) {
        file.previewElement.querySelector(".progress-bar").innerHTML = progress + "(%)";
    });
    TourImage.on("success", function (file, response) {
        if (typeof response == 'object') var r= response;
		else var r = jQuery.parseJSON(response);
        file.previewElement.querySelector(".image_name").value = r.file.name;
        file.previewElement.querySelector(".image_path").value = r.file.upload_path;
        setTimeout(function () {
            file.previewElement.querySelector(".action_buttons").remove();
            file.previewElement.querySelector(".file_progress").remove();
        }, 2000);
    });
    var submitButton = document.querySelector("#tsubmit");
    submitButton.addEventListener("click", function(evt) {
		evt.preventDefault();
		evt.stopPropagation();
		if (hasNewImage) {
			TourImage.enqueueFiles(TourImage.getFilesWithStatus(Dropzone.ADDED));
		} else {
			document.querySelector("#actions .start").click();
		}
	});
    TourImage.on("reset");
    TourImage.on("queuecomplete", function () {
        document.querySelector("#actions .cancel").setAttribute("disabled", "disabled");
        setTimeout(function () {
            document.querySelector("#actions .start").click();
        }, 2000);
    });
    document.querySelector("#actions .cancel").onclick = function () {
        TourImage.removeAllFiles(true);
        return false;
    };
function onTourChange(element) {
    var vendor = $(element).find(':selected').attr('vendor');
	$('#vendor').val(vendor);
}
</script>
